// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	v1alpha2 "github.com/kubernetes-csi/csi-proxy/client/api/iscsi/v1alpha2"
	impl "github.com/kubernetes-csi/csi-proxy/pkg/server/iscsi/impl"
)

func autoConvert_v1alpha2_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in *v1alpha2.AddTargetPortalRequest, out *impl.AddTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha2_AddTargetPortalRequest_To_impl_AddTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha2_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in *v1alpha2.AddTargetPortalRequest, out *impl.AddTargetPortalRequest) error {
	return autoConvert_v1alpha2_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in, out)
}

func autoConvert_impl_AddTargetPortalRequest_To_v1alpha2_AddTargetPortalRequest(in *impl.AddTargetPortalRequest, out *v1alpha2.AddTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_AddTargetPortalRequest_To_v1alpha2_AddTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_AddTargetPortalRequest_To_v1alpha2_AddTargetPortalRequest(in *impl.AddTargetPortalRequest, out *v1alpha2.AddTargetPortalRequest) error {
	return autoConvert_impl_AddTargetPortalRequest_To_v1alpha2_AddTargetPortalRequest(in, out)
}

func autoConvert_v1alpha2_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in *v1alpha2.AddTargetPortalResponse, out *impl.AddTargetPortalResponse) error {
	return nil
}

// Convert_v1alpha2_AddTargetPortalResponse_To_impl_AddTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha2_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in *v1alpha2.AddTargetPortalResponse, out *impl.AddTargetPortalResponse) error {
	return autoConvert_v1alpha2_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in, out)
}

func autoConvert_impl_AddTargetPortalResponse_To_v1alpha2_AddTargetPortalResponse(in *impl.AddTargetPortalResponse, out *v1alpha2.AddTargetPortalResponse) error {
	return nil
}

// Convert_impl_AddTargetPortalResponse_To_v1alpha2_AddTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_AddTargetPortalResponse_To_v1alpha2_AddTargetPortalResponse(in *impl.AddTargetPortalResponse, out *v1alpha2.AddTargetPortalResponse) error {
	return autoConvert_impl_AddTargetPortalResponse_To_v1alpha2_AddTargetPortalResponse(in, out)
}

func autoConvert_v1alpha2_ConnectTargetRequest_To_impl_ConnectTargetRequest(in *v1alpha2.ConnectTargetRequest, out *impl.ConnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	out.AuthType = impl.AuthenticationType(in.AuthType)
	out.ChapUsername = in.ChapUsername
	out.ChapSecret = in.ChapSecret
	return nil
}

// Convert_v1alpha2_ConnectTargetRequest_To_impl_ConnectTargetRequest is an autogenerated conversion function.
func Convert_v1alpha2_ConnectTargetRequest_To_impl_ConnectTargetRequest(in *v1alpha2.ConnectTargetRequest, out *impl.ConnectTargetRequest) error {
	return autoConvert_v1alpha2_ConnectTargetRequest_To_impl_ConnectTargetRequest(in, out)
}

func autoConvert_impl_ConnectTargetRequest_To_v1alpha2_ConnectTargetRequest(in *impl.ConnectTargetRequest, out *v1alpha2.ConnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	out.AuthType = v1alpha2.AuthenticationType(in.AuthType)
	out.ChapUsername = in.ChapUsername
	out.ChapSecret = in.ChapSecret
	return nil
}

// Convert_impl_ConnectTargetRequest_To_v1alpha2_ConnectTargetRequest is an autogenerated conversion function.
func Convert_impl_ConnectTargetRequest_To_v1alpha2_ConnectTargetRequest(in *impl.ConnectTargetRequest, out *v1alpha2.ConnectTargetRequest) error {
	return autoConvert_impl_ConnectTargetRequest_To_v1alpha2_ConnectTargetRequest(in, out)
}

func autoConvert_v1alpha2_ConnectTargetResponse_To_impl_ConnectTargetResponse(in *v1alpha2.ConnectTargetResponse, out *impl.ConnectTargetResponse) error {
	return nil
}

// Convert_v1alpha2_ConnectTargetResponse_To_impl_ConnectTargetResponse is an autogenerated conversion function.
func Convert_v1alpha2_ConnectTargetResponse_To_impl_ConnectTargetResponse(in *v1alpha2.ConnectTargetResponse, out *impl.ConnectTargetResponse) error {
	return autoConvert_v1alpha2_ConnectTargetResponse_To_impl_ConnectTargetResponse(in, out)
}

func autoConvert_impl_ConnectTargetResponse_To_v1alpha2_ConnectTargetResponse(in *impl.ConnectTargetResponse, out *v1alpha2.ConnectTargetResponse) error {
	return nil
}

// Convert_impl_ConnectTargetResponse_To_v1alpha2_ConnectTargetResponse is an autogenerated conversion function.
func Convert_impl_ConnectTargetResponse_To_v1alpha2_ConnectTargetResponse(in *impl.ConnectTargetResponse, out *v1alpha2.ConnectTargetResponse) error {
	return autoConvert_impl_ConnectTargetResponse_To_v1alpha2_ConnectTargetResponse(in, out)
}

func autoConvert_v1alpha2_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in *v1alpha2.DisconnectTargetRequest, out *impl.DisconnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_v1alpha2_DisconnectTargetRequest_To_impl_DisconnectTargetRequest is an autogenerated conversion function.
func Convert_v1alpha2_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in *v1alpha2.DisconnectTargetRequest, out *impl.DisconnectTargetRequest) error {
	return autoConvert_v1alpha2_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in, out)
}

func autoConvert_impl_DisconnectTargetRequest_To_v1alpha2_DisconnectTargetRequest(in *impl.DisconnectTargetRequest, out *v1alpha2.DisconnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_impl_DisconnectTargetRequest_To_v1alpha2_DisconnectTargetRequest is an autogenerated conversion function.
func Convert_impl_DisconnectTargetRequest_To_v1alpha2_DisconnectTargetRequest(in *impl.DisconnectTargetRequest, out *v1alpha2.DisconnectTargetRequest) error {
	return autoConvert_impl_DisconnectTargetRequest_To_v1alpha2_DisconnectTargetRequest(in, out)
}

func autoConvert_v1alpha2_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in *v1alpha2.DisconnectTargetResponse, out *impl.DisconnectTargetResponse) error {
	return nil
}

// Convert_v1alpha2_DisconnectTargetResponse_To_impl_DisconnectTargetResponse is an autogenerated conversion function.
func Convert_v1alpha2_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in *v1alpha2.DisconnectTargetResponse, out *impl.DisconnectTargetResponse) error {
	return autoConvert_v1alpha2_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in, out)
}

func autoConvert_impl_DisconnectTargetResponse_To_v1alpha2_DisconnectTargetResponse(in *impl.DisconnectTargetResponse, out *v1alpha2.DisconnectTargetResponse) error {
	return nil
}

// Convert_impl_DisconnectTargetResponse_To_v1alpha2_DisconnectTargetResponse is an autogenerated conversion function.
func Convert_impl_DisconnectTargetResponse_To_v1alpha2_DisconnectTargetResponse(in *impl.DisconnectTargetResponse, out *v1alpha2.DisconnectTargetResponse) error {
	return autoConvert_impl_DisconnectTargetResponse_To_v1alpha2_DisconnectTargetResponse(in, out)
}

func autoConvert_v1alpha2_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in *v1alpha2.DiscoverTargetPortalRequest, out *impl.DiscoverTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha2_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha2_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in *v1alpha2.DiscoverTargetPortalRequest, out *impl.DiscoverTargetPortalRequest) error {
	return autoConvert_v1alpha2_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in, out)
}

func autoConvert_impl_DiscoverTargetPortalRequest_To_v1alpha2_DiscoverTargetPortalRequest(in *impl.DiscoverTargetPortalRequest, out *v1alpha2.DiscoverTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_DiscoverTargetPortalRequest_To_v1alpha2_DiscoverTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_DiscoverTargetPortalRequest_To_v1alpha2_DiscoverTargetPortalRequest(in *impl.DiscoverTargetPortalRequest, out *v1alpha2.DiscoverTargetPortalRequest) error {
	return autoConvert_impl_DiscoverTargetPortalRequest_To_v1alpha2_DiscoverTargetPortalRequest(in, out)
}

func autoConvert_v1alpha2_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in *v1alpha2.DiscoverTargetPortalResponse, out *impl.DiscoverTargetPortalResponse) error {
	out.Iqns = *(*[]string)(unsafe.Pointer(&in.Iqns))
	return nil
}

// Convert_v1alpha2_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha2_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in *v1alpha2.DiscoverTargetPortalResponse, out *impl.DiscoverTargetPortalResponse) error {
	return autoConvert_v1alpha2_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in, out)
}

func autoConvert_impl_DiscoverTargetPortalResponse_To_v1alpha2_DiscoverTargetPortalResponse(in *impl.DiscoverTargetPortalResponse, out *v1alpha2.DiscoverTargetPortalResponse) error {
	out.Iqns = *(*[]string)(unsafe.Pointer(&in.Iqns))
	return nil
}

// Convert_impl_DiscoverTargetPortalResponse_To_v1alpha2_DiscoverTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_DiscoverTargetPortalResponse_To_v1alpha2_DiscoverTargetPortalResponse(in *impl.DiscoverTargetPortalResponse, out *v1alpha2.DiscoverTargetPortalResponse) error {
	return autoConvert_impl_DiscoverTargetPortalResponse_To_v1alpha2_DiscoverTargetPortalResponse(in, out)
}

func autoConvert_v1alpha2_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in *v1alpha2.GetTargetDisksRequest, out *impl.GetTargetDisksRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_v1alpha2_GetTargetDisksRequest_To_impl_GetTargetDisksRequest is an autogenerated conversion function.
func Convert_v1alpha2_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in *v1alpha2.GetTargetDisksRequest, out *impl.GetTargetDisksRequest) error {
	return autoConvert_v1alpha2_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in, out)
}

func autoConvert_impl_GetTargetDisksRequest_To_v1alpha2_GetTargetDisksRequest(in *impl.GetTargetDisksRequest, out *v1alpha2.GetTargetDisksRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_impl_GetTargetDisksRequest_To_v1alpha2_GetTargetDisksRequest is an autogenerated conversion function.
func Convert_impl_GetTargetDisksRequest_To_v1alpha2_GetTargetDisksRequest(in *impl.GetTargetDisksRequest, out *v1alpha2.GetTargetDisksRequest) error {
	return autoConvert_impl_GetTargetDisksRequest_To_v1alpha2_GetTargetDisksRequest(in, out)
}

func autoConvert_v1alpha2_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in *v1alpha2.GetTargetDisksResponse, out *impl.GetTargetDisksResponse) error {
	out.DiskIDs = *(*[]string)(unsafe.Pointer(&in.DiskIDs))
	return nil
}

// Convert_v1alpha2_GetTargetDisksResponse_To_impl_GetTargetDisksResponse is an autogenerated conversion function.
func Convert_v1alpha2_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in *v1alpha2.GetTargetDisksResponse, out *impl.GetTargetDisksResponse) error {
	return autoConvert_v1alpha2_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in, out)
}

func autoConvert_impl_GetTargetDisksResponse_To_v1alpha2_GetTargetDisksResponse(in *impl.GetTargetDisksResponse, out *v1alpha2.GetTargetDisksResponse) error {
	out.DiskIDs = *(*[]string)(unsafe.Pointer(&in.DiskIDs))
	return nil
}

// Convert_impl_GetTargetDisksResponse_To_v1alpha2_GetTargetDisksResponse is an autogenerated conversion function.
func Convert_impl_GetTargetDisksResponse_To_v1alpha2_GetTargetDisksResponse(in *impl.GetTargetDisksResponse, out *v1alpha2.GetTargetDisksResponse) error {
	return autoConvert_impl_GetTargetDisksResponse_To_v1alpha2_GetTargetDisksResponse(in, out)
}

func autoConvert_v1alpha2_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in *v1alpha2.ListTargetPortalsRequest, out *impl.ListTargetPortalsRequest) error {
	return nil
}

// Convert_v1alpha2_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest is an autogenerated conversion function.
func Convert_v1alpha2_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in *v1alpha2.ListTargetPortalsRequest, out *impl.ListTargetPortalsRequest) error {
	return autoConvert_v1alpha2_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in, out)
}

func autoConvert_impl_ListTargetPortalsRequest_To_v1alpha2_ListTargetPortalsRequest(in *impl.ListTargetPortalsRequest, out *v1alpha2.ListTargetPortalsRequest) error {
	return nil
}

// Convert_impl_ListTargetPortalsRequest_To_v1alpha2_ListTargetPortalsRequest is an autogenerated conversion function.
func Convert_impl_ListTargetPortalsRequest_To_v1alpha2_ListTargetPortalsRequest(in *impl.ListTargetPortalsRequest, out *v1alpha2.ListTargetPortalsRequest) error {
	return autoConvert_impl_ListTargetPortalsRequest_To_v1alpha2_ListTargetPortalsRequest(in, out)
}

func autoConvert_v1alpha2_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in *v1alpha2.ListTargetPortalsResponse, out *impl.ListTargetPortalsResponse) error {
	if in.TargetPortals != nil {
		in, out := &in.TargetPortals, &out.TargetPortals
		*out = make([]*impl.TargetPortal, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*&(*in)[i], *&(*out)[i]); err != nil {
				return err
			}
		}
	} else {
		out.TargetPortals = nil
	}
	return nil
}

// Convert_v1alpha2_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse is an autogenerated conversion function.
func Convert_v1alpha2_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in *v1alpha2.ListTargetPortalsResponse, out *impl.ListTargetPortalsResponse) error {
	return autoConvert_v1alpha2_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in, out)
}

// detected external conversion function
// Convert_impl_ListTargetPortalsResponse_To_v1alpha2_ListTargetPortalsResponse(in *impl.ListTargetPortalsResponse, out *v1alpha2.ListTargetPortalsResponse) error
// skipping generation of the auto function

func autoConvert_v1alpha2_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in *v1alpha2.RemoveTargetPortalRequest, out *impl.RemoveTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha2_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha2_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in *v1alpha2.RemoveTargetPortalRequest, out *impl.RemoveTargetPortalRequest) error {
	return autoConvert_v1alpha2_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in, out)
}

func autoConvert_impl_RemoveTargetPortalRequest_To_v1alpha2_RemoveTargetPortalRequest(in *impl.RemoveTargetPortalRequest, out *v1alpha2.RemoveTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha2.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_RemoveTargetPortalRequest_To_v1alpha2_RemoveTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_RemoveTargetPortalRequest_To_v1alpha2_RemoveTargetPortalRequest(in *impl.RemoveTargetPortalRequest, out *v1alpha2.RemoveTargetPortalRequest) error {
	return autoConvert_impl_RemoveTargetPortalRequest_To_v1alpha2_RemoveTargetPortalRequest(in, out)
}

func autoConvert_v1alpha2_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in *v1alpha2.RemoveTargetPortalResponse, out *impl.RemoveTargetPortalResponse) error {
	return nil
}

// Convert_v1alpha2_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha2_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in *v1alpha2.RemoveTargetPortalResponse, out *impl.RemoveTargetPortalResponse) error {
	return autoConvert_v1alpha2_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in, out)
}

func autoConvert_impl_RemoveTargetPortalResponse_To_v1alpha2_RemoveTargetPortalResponse(in *impl.RemoveTargetPortalResponse, out *v1alpha2.RemoveTargetPortalResponse) error {
	return nil
}

// Convert_impl_RemoveTargetPortalResponse_To_v1alpha2_RemoveTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_RemoveTargetPortalResponse_To_v1alpha2_RemoveTargetPortalResponse(in *impl.RemoveTargetPortalResponse, out *v1alpha2.RemoveTargetPortalResponse) error {
	return autoConvert_impl_RemoveTargetPortalResponse_To_v1alpha2_RemoveTargetPortalResponse(in, out)
}

func autoConvert_v1alpha2_SetMutualChapSecretRequest_To_impl_SetMutualChapSecretRequest(in *v1alpha2.SetMutualChapSecretRequest, out *impl.SetMutualChapSecretRequest) error {
	out.MutualChapSecret = in.MutualChapSecret
	return nil
}

// Convert_v1alpha2_SetMutualChapSecretRequest_To_impl_SetMutualChapSecretRequest is an autogenerated conversion function.
func Convert_v1alpha2_SetMutualChapSecretRequest_To_impl_SetMutualChapSecretRequest(in *v1alpha2.SetMutualChapSecretRequest, out *impl.SetMutualChapSecretRequest) error {
	return autoConvert_v1alpha2_SetMutualChapSecretRequest_To_impl_SetMutualChapSecretRequest(in, out)
}

func autoConvert_impl_SetMutualChapSecretRequest_To_v1alpha2_SetMutualChapSecretRequest(in *impl.SetMutualChapSecretRequest, out *v1alpha2.SetMutualChapSecretRequest) error {
	out.MutualChapSecret = in.MutualChapSecret
	return nil
}

// Convert_impl_SetMutualChapSecretRequest_To_v1alpha2_SetMutualChapSecretRequest is an autogenerated conversion function.
func Convert_impl_SetMutualChapSecretRequest_To_v1alpha2_SetMutualChapSecretRequest(in *impl.SetMutualChapSecretRequest, out *v1alpha2.SetMutualChapSecretRequest) error {
	return autoConvert_impl_SetMutualChapSecretRequest_To_v1alpha2_SetMutualChapSecretRequest(in, out)
}

func autoConvert_v1alpha2_SetMutualChapSecretResponse_To_impl_SetMutualChapSecretResponse(in *v1alpha2.SetMutualChapSecretResponse, out *impl.SetMutualChapSecretResponse) error {
	return nil
}

// Convert_v1alpha2_SetMutualChapSecretResponse_To_impl_SetMutualChapSecretResponse is an autogenerated conversion function.
func Convert_v1alpha2_SetMutualChapSecretResponse_To_impl_SetMutualChapSecretResponse(in *v1alpha2.SetMutualChapSecretResponse, out *impl.SetMutualChapSecretResponse) error {
	return autoConvert_v1alpha2_SetMutualChapSecretResponse_To_impl_SetMutualChapSecretResponse(in, out)
}

func autoConvert_impl_SetMutualChapSecretResponse_To_v1alpha2_SetMutualChapSecretResponse(in *impl.SetMutualChapSecretResponse, out *v1alpha2.SetMutualChapSecretResponse) error {
	return nil
}

// Convert_impl_SetMutualChapSecretResponse_To_v1alpha2_SetMutualChapSecretResponse is an autogenerated conversion function.
func Convert_impl_SetMutualChapSecretResponse_To_v1alpha2_SetMutualChapSecretResponse(in *impl.SetMutualChapSecretResponse, out *v1alpha2.SetMutualChapSecretResponse) error {
	return autoConvert_impl_SetMutualChapSecretResponse_To_v1alpha2_SetMutualChapSecretResponse(in, out)
}

func autoConvert_v1alpha2_TargetPortal_To_impl_TargetPortal(in *v1alpha2.TargetPortal, out *impl.TargetPortal) error {
	out.TargetAddress = in.TargetAddress
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1alpha2_TargetPortal_To_impl_TargetPortal is an autogenerated conversion function.
func Convert_v1alpha2_TargetPortal_To_impl_TargetPortal(in *v1alpha2.TargetPortal, out *impl.TargetPortal) error {
	return autoConvert_v1alpha2_TargetPortal_To_impl_TargetPortal(in, out)
}

func autoConvert_impl_TargetPortal_To_v1alpha2_TargetPortal(in *impl.TargetPortal, out *v1alpha2.TargetPortal) error {
	out.TargetAddress = in.TargetAddress
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_impl_TargetPortal_To_v1alpha2_TargetPortal is an autogenerated conversion function.
func Convert_impl_TargetPortal_To_v1alpha2_TargetPortal(in *impl.TargetPortal, out *v1alpha2.TargetPortal) error {
	return autoConvert_impl_TargetPortal_To_v1alpha2_TargetPortal(in, out)
}
