// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBIOSSerialNumberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBIOSSerialNumberRequest) Reset()         { *m = GetBIOSSerialNumberRequest{} }
func (m *GetBIOSSerialNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetBIOSSerialNumberRequest) ProtoMessage()    {}
func (*GetBIOSSerialNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_714d71facb074551, []int{0}
}

func (m *GetBIOSSerialNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBIOSSerialNumberRequest.Unmarshal(m, b)
}
func (m *GetBIOSSerialNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBIOSSerialNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetBIOSSerialNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBIOSSerialNumberRequest.Merge(m, src)
}
func (m *GetBIOSSerialNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetBIOSSerialNumberRequest.Size(m)
}
func (m *GetBIOSSerialNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBIOSSerialNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBIOSSerialNumberRequest proto.InternalMessageInfo

type GetBIOSSerialNumberResponse struct {
	// Serial number
	SerialNumber         string   `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBIOSSerialNumberResponse) Reset()         { *m = GetBIOSSerialNumberResponse{} }
func (m *GetBIOSSerialNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetBIOSSerialNumberResponse) ProtoMessage()    {}
func (*GetBIOSSerialNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_714d71facb074551, []int{1}
}

func (m *GetBIOSSerialNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBIOSSerialNumberResponse.Unmarshal(m, b)
}
func (m *GetBIOSSerialNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBIOSSerialNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetBIOSSerialNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBIOSSerialNumberResponse.Merge(m, src)
}
func (m *GetBIOSSerialNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetBIOSSerialNumberResponse.Size(m)
}
func (m *GetBIOSSerialNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBIOSSerialNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBIOSSerialNumberResponse proto.InternalMessageInfo

func (m *GetBIOSSerialNumberResponse) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBIOSSerialNumberRequest)(nil), "v1alpha1.GetBIOSSerialNumberRequest")
	proto.RegisterType((*GetBIOSSerialNumberResponse)(nil), "v1alpha1.GetBIOSSerialNumberResponse")
}

func init() {
	proto.RegisterFile("src/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto", fileDescriptor_714d71facb074551)
}

var fileDescriptor_714d71facb074551 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x29, 0x2e, 0x4a, 0xd6,
	0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2e, 0x4d, 0x4a, 0x2d,
	0xca, 0x4b, 0x2d, 0x49, 0x2d, 0xd6, 0x4d, 0x2e, 0xce, 0xd4, 0x4f, 0x2e, 0xce, 0xd4, 0x2d, 0x28,
	0xca, 0xaf, 0xa8, 0xd4, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f,
	0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0x2f, 0x33, 0x4c, 0xcc, 0x29, 0xc8, 0x48, 0x34, 0x04, 0x89,
	0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x71, 0xc0, 0xc4, 0x94, 0x64, 0xb8, 0xa4, 0xdc, 0x53,
	0x4b, 0x9c, 0x3c, 0xfd, 0x83, 0x83, 0x53, 0x8b, 0x32, 0x13, 0x73, 0xfc, 0x4a, 0x73, 0x93, 0x52,
	0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x9c, 0xb8, 0xa4, 0xb1, 0xca, 0x16, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x73, 0xf1, 0x16, 0x83, 0xc5, 0xe3, 0xf3, 0xc0, 0x12, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x3c, 0xc5, 0x48, 0x8a, 0x8d, 0xf2, 0xb8, 0xd8, 0x82, 0xc1,
	0x0e, 0x11, 0x4a, 0xe1, 0x12, 0xc6, 0x62, 0x9a, 0x90, 0x8a, 0x1e, 0xcc, 0x35, 0x7a, 0xb8, 0x9d,
	0x22, 0xa5, 0x4a, 0x40, 0x15, 0xc4, 0x49, 0x4a, 0x0c, 0x4e, 0x0e, 0x51, 0x76, 0x94, 0x85, 0x53,
	0x12, 0x1b, 0x38, 0x90, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x01, 0xa9, 0x3f, 0x74,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	// GetBIOSSerialNumber returns the device's serial number
	GetBIOSSerialNumber(ctx context.Context, in *GetBIOSSerialNumberRequest, opts ...grpc.CallOption) (*GetBIOSSerialNumberResponse, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) GetBIOSSerialNumber(ctx context.Context, in *GetBIOSSerialNumberRequest, opts ...grpc.CallOption) (*GetBIOSSerialNumberResponse, error) {
	out := new(GetBIOSSerialNumberResponse)
	err := c.cc.Invoke(ctx, "/v1alpha1.System/GetBIOSSerialNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	// GetBIOSSerialNumber returns the device's serial number
	GetBIOSSerialNumber(context.Context, *GetBIOSSerialNumberRequest) (*GetBIOSSerialNumberResponse, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) GetBIOSSerialNumber(ctx context.Context, req *GetBIOSSerialNumberRequest) (*GetBIOSSerialNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBIOSSerialNumber not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_GetBIOSSerialNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBIOSSerialNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).GetBIOSSerialNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.System/GetBIOSSerialNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).GetBIOSSerialNumber(ctx, req.(*GetBIOSSerialNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha1.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBIOSSerialNumber",
			Handler:    _System_GetBIOSSerialNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto",
}
