// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-csi/csi-proxy/client/api/smb/v1alpha1"
	internal "github.com/kubernetes-csi/csi-proxy/internal/server/smb/internal"
)

func autoConvert_v1alpha1_MountSmbShareRequest_To_internal_MountSmbShareRequest(in *v1alpha1.MountSmbShareRequest, out *internal.MountSmbShareRequest) error {
	out.RemotePath = in.RemotePath
	out.LocalPath = in.LocalPath
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1alpha1_MountSmbShareRequest_To_internal_MountSmbShareRequest is an autogenerated conversion function.
func Convert_v1alpha1_MountSmbShareRequest_To_internal_MountSmbShareRequest(in *v1alpha1.MountSmbShareRequest, out *internal.MountSmbShareRequest) error {
	return autoConvert_v1alpha1_MountSmbShareRequest_To_internal_MountSmbShareRequest(in, out)
}

func autoConvert_internal_MountSmbShareRequest_To_v1alpha1_MountSmbShareRequest(in *internal.MountSmbShareRequest, out *v1alpha1.MountSmbShareRequest) error {
	out.RemotePath = in.RemotePath
	out.LocalPath = in.LocalPath
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_internal_MountSmbShareRequest_To_v1alpha1_MountSmbShareRequest is an autogenerated conversion function.
func Convert_internal_MountSmbShareRequest_To_v1alpha1_MountSmbShareRequest(in *internal.MountSmbShareRequest, out *v1alpha1.MountSmbShareRequest) error {
	return autoConvert_internal_MountSmbShareRequest_To_v1alpha1_MountSmbShareRequest(in, out)
}

func autoConvert_v1alpha1_MountSmbShareResponse_To_internal_MountSmbShareResponse(in *v1alpha1.MountSmbShareResponse, out *internal.MountSmbShareResponse) error {
	out.Error = in.Error
	return nil
}

// Convert_v1alpha1_MountSmbShareResponse_To_internal_MountSmbShareResponse is an autogenerated conversion function.
func Convert_v1alpha1_MountSmbShareResponse_To_internal_MountSmbShareResponse(in *v1alpha1.MountSmbShareResponse, out *internal.MountSmbShareResponse) error {
	return autoConvert_v1alpha1_MountSmbShareResponse_To_internal_MountSmbShareResponse(in, out)
}

func autoConvert_internal_MountSmbShareResponse_To_v1alpha1_MountSmbShareResponse(in *internal.MountSmbShareResponse, out *v1alpha1.MountSmbShareResponse) error {
	out.Error = in.Error
	return nil
}

// Convert_internal_MountSmbShareResponse_To_v1alpha1_MountSmbShareResponse is an autogenerated conversion function.
func Convert_internal_MountSmbShareResponse_To_v1alpha1_MountSmbShareResponse(in *internal.MountSmbShareResponse, out *v1alpha1.MountSmbShareResponse) error {
	return autoConvert_internal_MountSmbShareResponse_To_v1alpha1_MountSmbShareResponse(in, out)
}

func autoConvert_v1alpha1_UnmountSmbShareRequest_To_internal_UnmountSmbShareRequest(in *v1alpha1.UnmountSmbShareRequest, out *internal.UnmountSmbShareRequest) error {
	out.RemotePath = in.RemotePath
	out.LocalPath = in.LocalPath
	return nil
}

// Convert_v1alpha1_UnmountSmbShareRequest_To_internal_UnmountSmbShareRequest is an autogenerated conversion function.
func Convert_v1alpha1_UnmountSmbShareRequest_To_internal_UnmountSmbShareRequest(in *v1alpha1.UnmountSmbShareRequest, out *internal.UnmountSmbShareRequest) error {
	return autoConvert_v1alpha1_UnmountSmbShareRequest_To_internal_UnmountSmbShareRequest(in, out)
}

func autoConvert_internal_UnmountSmbShareRequest_To_v1alpha1_UnmountSmbShareRequest(in *internal.UnmountSmbShareRequest, out *v1alpha1.UnmountSmbShareRequest) error {
	out.RemotePath = in.RemotePath
	out.LocalPath = in.LocalPath
	return nil
}

// Convert_internal_UnmountSmbShareRequest_To_v1alpha1_UnmountSmbShareRequest is an autogenerated conversion function.
func Convert_internal_UnmountSmbShareRequest_To_v1alpha1_UnmountSmbShareRequest(in *internal.UnmountSmbShareRequest, out *v1alpha1.UnmountSmbShareRequest) error {
	return autoConvert_internal_UnmountSmbShareRequest_To_v1alpha1_UnmountSmbShareRequest(in, out)
}

func autoConvert_v1alpha1_UnmountSmbShareResponse_To_internal_UnmountSmbShareResponse(in *v1alpha1.UnmountSmbShareResponse, out *internal.UnmountSmbShareResponse) error {
	out.Error = in.Error
	return nil
}

// Convert_v1alpha1_UnmountSmbShareResponse_To_internal_UnmountSmbShareResponse is an autogenerated conversion function.
func Convert_v1alpha1_UnmountSmbShareResponse_To_internal_UnmountSmbShareResponse(in *v1alpha1.UnmountSmbShareResponse, out *internal.UnmountSmbShareResponse) error {
	return autoConvert_v1alpha1_UnmountSmbShareResponse_To_internal_UnmountSmbShareResponse(in, out)
}

func autoConvert_internal_UnmountSmbShareResponse_To_v1alpha1_UnmountSmbShareResponse(in *internal.UnmountSmbShareResponse, out *v1alpha1.UnmountSmbShareResponse) error {
	out.Error = in.Error
	return nil
}

// Convert_internal_UnmountSmbShareResponse_To_v1alpha1_UnmountSmbShareResponse is an autogenerated conversion function.
func Convert_internal_UnmountSmbShareResponse_To_v1alpha1_UnmountSmbShareResponse(in *internal.UnmountSmbShareResponse, out *v1alpha1.UnmountSmbShareResponse) error {
	return autoConvert_internal_UnmountSmbShareResponse_To_v1alpha1_UnmountSmbShareResponse(in, out)
}
