// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package volume

import (
	"github.com/kubernetes-csi/csi-proxy/client/apiversion"
	srvtypes "github.com/kubernetes-csi/csi-proxy/internal/server/types"
	"github.com/kubernetes-csi/csi-proxy/internal/server/volume/internal"
	"github.com/kubernetes-csi/csi-proxy/internal/server/volume/internal/v1alpha1"
	"github.com/kubernetes-csi/csi-proxy/internal/server/volume/internal/v1beta1"
)

const name = "volume"

// ensure the server defines all the required methods
var _ internal.ServerInterface = &Server{}

func (s *Server) VersionedAPIs() []*srvtypes.VersionedAPI {
	v1alpha1Server := v1alpha1.NewVersionedServer(s)
	v1beta1Server := v1beta1.NewVersionedServer(s)

	return []*srvtypes.VersionedAPI{
		{
			Group:      name,
			Version:    apiversion.NewVersionOrPanic("v1alpha1"),
			Registrant: v1alpha1Server.Register,
		},
		{
			Group:      name,
			Version:    apiversion.NewVersionOrPanic("v1beta1"),
			Registrant: v1beta1Server.Register,
		},
	}
}
