// Code generated by csi-proxy-gen. DO NOT EDIT.

package dummy

import (
	"github.com/kubernetes-csi/csi-proxy/internal/apiversion"
	"github.com/kubernetes-csi/csi-proxy/internal/server"
	"github.com/kubernetes-csi/csi-proxy/internal/server/filesystem/internal"
	"github.com/kubernetes-csi/csi-proxy/internal/server/filesystem/internal/v1alpha1"
)

const name = "filesystem"

// ensure the server defines all the required methods
var _ internal.ServerInterface = &Server{}

func (s *Server) VersionedAPIs() []*server.VersionedAPI {
	v1alpha1Server := v1alpha1.NewVersionedServer(s)

	return []*server.VersionedAPI{
		{
			Group:      name,
			Version:    apiversion.NewVersionOrPanic("v1alpha1"),
			Registrant: v1alpha1Server.Register,
		},
	}
}
