// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1beta3

import (
	unsafe "unsafe"

	v1beta3 "github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta3"
	internal "github.com/kubernetes-csi/csi-proxy/internal/server/volume/internal"
)

func autoConvert_v1beta3_FormatVolumeRequest_To_internal_FormatVolumeRequest(in *v1beta3.FormatVolumeRequest, out *internal.FormatVolumeRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_FormatVolumeRequest_To_internal_FormatVolumeRequest is an autogenerated conversion function.
func Convert_v1beta3_FormatVolumeRequest_To_internal_FormatVolumeRequest(in *v1beta3.FormatVolumeRequest, out *internal.FormatVolumeRequest) error {
	return autoConvert_v1beta3_FormatVolumeRequest_To_internal_FormatVolumeRequest(in, out)
}

func autoConvert_internal_FormatVolumeRequest_To_v1beta3_FormatVolumeRequest(in *internal.FormatVolumeRequest, out *v1beta3.FormatVolumeRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_FormatVolumeRequest_To_v1beta3_FormatVolumeRequest is an autogenerated conversion function.
func Convert_internal_FormatVolumeRequest_To_v1beta3_FormatVolumeRequest(in *internal.FormatVolumeRequest, out *v1beta3.FormatVolumeRequest) error {
	return autoConvert_internal_FormatVolumeRequest_To_v1beta3_FormatVolumeRequest(in, out)
}

func autoConvert_v1beta3_FormatVolumeResponse_To_internal_FormatVolumeResponse(in *v1beta3.FormatVolumeResponse, out *internal.FormatVolumeResponse) error {
	return nil
}

// Convert_v1beta3_FormatVolumeResponse_To_internal_FormatVolumeResponse is an autogenerated conversion function.
func Convert_v1beta3_FormatVolumeResponse_To_internal_FormatVolumeResponse(in *v1beta3.FormatVolumeResponse, out *internal.FormatVolumeResponse) error {
	return autoConvert_v1beta3_FormatVolumeResponse_To_internal_FormatVolumeResponse(in, out)
}

func autoConvert_internal_FormatVolumeResponse_To_v1beta3_FormatVolumeResponse(in *internal.FormatVolumeResponse, out *v1beta3.FormatVolumeResponse) error {
	return nil
}

// Convert_internal_FormatVolumeResponse_To_v1beta3_FormatVolumeResponse is an autogenerated conversion function.
func Convert_internal_FormatVolumeResponse_To_v1beta3_FormatVolumeResponse(in *internal.FormatVolumeResponse, out *v1beta3.FormatVolumeResponse) error {
	return autoConvert_internal_FormatVolumeResponse_To_v1beta3_FormatVolumeResponse(in, out)
}

func autoConvert_v1beta3_GetDiskNumberFromVolumeIDRequest_To_internal_GetDiskNumberFromVolumeIDRequest(in *v1beta3.GetDiskNumberFromVolumeIDRequest, out *internal.GetDiskNumberFromVolumeIDRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_GetDiskNumberFromVolumeIDRequest_To_internal_GetDiskNumberFromVolumeIDRequest is an autogenerated conversion function.
func Convert_v1beta3_GetDiskNumberFromVolumeIDRequest_To_internal_GetDiskNumberFromVolumeIDRequest(in *v1beta3.GetDiskNumberFromVolumeIDRequest, out *internal.GetDiskNumberFromVolumeIDRequest) error {
	return autoConvert_v1beta3_GetDiskNumberFromVolumeIDRequest_To_internal_GetDiskNumberFromVolumeIDRequest(in, out)
}

func autoConvert_internal_GetDiskNumberFromVolumeIDRequest_To_v1beta3_GetDiskNumberFromVolumeIDRequest(in *internal.GetDiskNumberFromVolumeIDRequest, out *v1beta3.GetDiskNumberFromVolumeIDRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_GetDiskNumberFromVolumeIDRequest_To_v1beta3_GetDiskNumberFromVolumeIDRequest is an autogenerated conversion function.
func Convert_internal_GetDiskNumberFromVolumeIDRequest_To_v1beta3_GetDiskNumberFromVolumeIDRequest(in *internal.GetDiskNumberFromVolumeIDRequest, out *v1beta3.GetDiskNumberFromVolumeIDRequest) error {
	return autoConvert_internal_GetDiskNumberFromVolumeIDRequest_To_v1beta3_GetDiskNumberFromVolumeIDRequest(in, out)
}

func autoConvert_v1beta3_GetDiskNumberFromVolumeIDResponse_To_internal_GetDiskNumberFromVolumeIDResponse(in *v1beta3.GetDiskNumberFromVolumeIDResponse, out *internal.GetDiskNumberFromVolumeIDResponse) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_v1beta3_GetDiskNumberFromVolumeIDResponse_To_internal_GetDiskNumberFromVolumeIDResponse is an autogenerated conversion function.
func Convert_v1beta3_GetDiskNumberFromVolumeIDResponse_To_internal_GetDiskNumberFromVolumeIDResponse(in *v1beta3.GetDiskNumberFromVolumeIDResponse, out *internal.GetDiskNumberFromVolumeIDResponse) error {
	return autoConvert_v1beta3_GetDiskNumberFromVolumeIDResponse_To_internal_GetDiskNumberFromVolumeIDResponse(in, out)
}

func autoConvert_internal_GetDiskNumberFromVolumeIDResponse_To_v1beta3_GetDiskNumberFromVolumeIDResponse(in *internal.GetDiskNumberFromVolumeIDResponse, out *v1beta3.GetDiskNumberFromVolumeIDResponse) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_internal_GetDiskNumberFromVolumeIDResponse_To_v1beta3_GetDiskNumberFromVolumeIDResponse is an autogenerated conversion function.
func Convert_internal_GetDiskNumberFromVolumeIDResponse_To_v1beta3_GetDiskNumberFromVolumeIDResponse(in *internal.GetDiskNumberFromVolumeIDResponse, out *v1beta3.GetDiskNumberFromVolumeIDResponse) error {
	return autoConvert_internal_GetDiskNumberFromVolumeIDResponse_To_v1beta3_GetDiskNumberFromVolumeIDResponse(in, out)
}

func autoConvert_v1beta3_GetVolumeIDFromTargetPathRequest_To_internal_GetVolumeIDFromTargetPathRequest(in *v1beta3.GetVolumeIDFromTargetPathRequest, out *internal.GetVolumeIDFromTargetPathRequest) error {
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_v1beta3_GetVolumeIDFromTargetPathRequest_To_internal_GetVolumeIDFromTargetPathRequest is an autogenerated conversion function.
func Convert_v1beta3_GetVolumeIDFromTargetPathRequest_To_internal_GetVolumeIDFromTargetPathRequest(in *v1beta3.GetVolumeIDFromTargetPathRequest, out *internal.GetVolumeIDFromTargetPathRequest) error {
	return autoConvert_v1beta3_GetVolumeIDFromTargetPathRequest_To_internal_GetVolumeIDFromTargetPathRequest(in, out)
}

func autoConvert_internal_GetVolumeIDFromTargetPathRequest_To_v1beta3_GetVolumeIDFromTargetPathRequest(in *internal.GetVolumeIDFromTargetPathRequest, out *v1beta3.GetVolumeIDFromTargetPathRequest) error {
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_internal_GetVolumeIDFromTargetPathRequest_To_v1beta3_GetVolumeIDFromTargetPathRequest is an autogenerated conversion function.
func Convert_internal_GetVolumeIDFromTargetPathRequest_To_v1beta3_GetVolumeIDFromTargetPathRequest(in *internal.GetVolumeIDFromTargetPathRequest, out *v1beta3.GetVolumeIDFromTargetPathRequest) error {
	return autoConvert_internal_GetVolumeIDFromTargetPathRequest_To_v1beta3_GetVolumeIDFromTargetPathRequest(in, out)
}

func autoConvert_v1beta3_GetVolumeIDFromTargetPathResponse_To_internal_GetVolumeIDFromTargetPathResponse(in *v1beta3.GetVolumeIDFromTargetPathResponse, out *internal.GetVolumeIDFromTargetPathResponse) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_GetVolumeIDFromTargetPathResponse_To_internal_GetVolumeIDFromTargetPathResponse is an autogenerated conversion function.
func Convert_v1beta3_GetVolumeIDFromTargetPathResponse_To_internal_GetVolumeIDFromTargetPathResponse(in *v1beta3.GetVolumeIDFromTargetPathResponse, out *internal.GetVolumeIDFromTargetPathResponse) error {
	return autoConvert_v1beta3_GetVolumeIDFromTargetPathResponse_To_internal_GetVolumeIDFromTargetPathResponse(in, out)
}

func autoConvert_internal_GetVolumeIDFromTargetPathResponse_To_v1beta3_GetVolumeIDFromTargetPathResponse(in *internal.GetVolumeIDFromTargetPathResponse, out *v1beta3.GetVolumeIDFromTargetPathResponse) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_GetVolumeIDFromTargetPathResponse_To_v1beta3_GetVolumeIDFromTargetPathResponse is an autogenerated conversion function.
func Convert_internal_GetVolumeIDFromTargetPathResponse_To_v1beta3_GetVolumeIDFromTargetPathResponse(in *internal.GetVolumeIDFromTargetPathResponse, out *v1beta3.GetVolumeIDFromTargetPathResponse) error {
	return autoConvert_internal_GetVolumeIDFromTargetPathResponse_To_v1beta3_GetVolumeIDFromTargetPathResponse(in, out)
}

func autoConvert_v1beta3_GetVolumeStatsRequest_To_internal_GetVolumeStatsRequest(in *v1beta3.GetVolumeStatsRequest, out *internal.GetVolumeStatsRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_GetVolumeStatsRequest_To_internal_GetVolumeStatsRequest is an autogenerated conversion function.
func Convert_v1beta3_GetVolumeStatsRequest_To_internal_GetVolumeStatsRequest(in *v1beta3.GetVolumeStatsRequest, out *internal.GetVolumeStatsRequest) error {
	return autoConvert_v1beta3_GetVolumeStatsRequest_To_internal_GetVolumeStatsRequest(in, out)
}

func autoConvert_internal_GetVolumeStatsRequest_To_v1beta3_GetVolumeStatsRequest(in *internal.GetVolumeStatsRequest, out *v1beta3.GetVolumeStatsRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_GetVolumeStatsRequest_To_v1beta3_GetVolumeStatsRequest is an autogenerated conversion function.
func Convert_internal_GetVolumeStatsRequest_To_v1beta3_GetVolumeStatsRequest(in *internal.GetVolumeStatsRequest, out *v1beta3.GetVolumeStatsRequest) error {
	return autoConvert_internal_GetVolumeStatsRequest_To_v1beta3_GetVolumeStatsRequest(in, out)
}

func autoConvert_v1beta3_GetVolumeStatsResponse_To_internal_GetVolumeStatsResponse(in *v1beta3.GetVolumeStatsResponse, out *internal.GetVolumeStatsResponse) error {
	out.TotalBytes = in.TotalBytes
	out.UsedBytes = in.UsedBytes
	return nil
}

// Convert_v1beta3_GetVolumeStatsResponse_To_internal_GetVolumeStatsResponse is an autogenerated conversion function.
func Convert_v1beta3_GetVolumeStatsResponse_To_internal_GetVolumeStatsResponse(in *v1beta3.GetVolumeStatsResponse, out *internal.GetVolumeStatsResponse) error {
	return autoConvert_v1beta3_GetVolumeStatsResponse_To_internal_GetVolumeStatsResponse(in, out)
}

func autoConvert_internal_GetVolumeStatsResponse_To_v1beta3_GetVolumeStatsResponse(in *internal.GetVolumeStatsResponse, out *v1beta3.GetVolumeStatsResponse) error {
	out.TotalBytes = in.TotalBytes
	out.UsedBytes = in.UsedBytes
	return nil
}

// Convert_internal_GetVolumeStatsResponse_To_v1beta3_GetVolumeStatsResponse is an autogenerated conversion function.
func Convert_internal_GetVolumeStatsResponse_To_v1beta3_GetVolumeStatsResponse(in *internal.GetVolumeStatsResponse, out *v1beta3.GetVolumeStatsResponse) error {
	return autoConvert_internal_GetVolumeStatsResponse_To_v1beta3_GetVolumeStatsResponse(in, out)
}

func autoConvert_v1beta3_IsVolumeFormattedRequest_To_internal_IsVolumeFormattedRequest(in *v1beta3.IsVolumeFormattedRequest, out *internal.IsVolumeFormattedRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_IsVolumeFormattedRequest_To_internal_IsVolumeFormattedRequest is an autogenerated conversion function.
func Convert_v1beta3_IsVolumeFormattedRequest_To_internal_IsVolumeFormattedRequest(in *v1beta3.IsVolumeFormattedRequest, out *internal.IsVolumeFormattedRequest) error {
	return autoConvert_v1beta3_IsVolumeFormattedRequest_To_internal_IsVolumeFormattedRequest(in, out)
}

func autoConvert_internal_IsVolumeFormattedRequest_To_v1beta3_IsVolumeFormattedRequest(in *internal.IsVolumeFormattedRequest, out *v1beta3.IsVolumeFormattedRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_IsVolumeFormattedRequest_To_v1beta3_IsVolumeFormattedRequest is an autogenerated conversion function.
func Convert_internal_IsVolumeFormattedRequest_To_v1beta3_IsVolumeFormattedRequest(in *internal.IsVolumeFormattedRequest, out *v1beta3.IsVolumeFormattedRequest) error {
	return autoConvert_internal_IsVolumeFormattedRequest_To_v1beta3_IsVolumeFormattedRequest(in, out)
}

func autoConvert_v1beta3_IsVolumeFormattedResponse_To_internal_IsVolumeFormattedResponse(in *v1beta3.IsVolumeFormattedResponse, out *internal.IsVolumeFormattedResponse) error {
	out.Formatted = in.Formatted
	return nil
}

// Convert_v1beta3_IsVolumeFormattedResponse_To_internal_IsVolumeFormattedResponse is an autogenerated conversion function.
func Convert_v1beta3_IsVolumeFormattedResponse_To_internal_IsVolumeFormattedResponse(in *v1beta3.IsVolumeFormattedResponse, out *internal.IsVolumeFormattedResponse) error {
	return autoConvert_v1beta3_IsVolumeFormattedResponse_To_internal_IsVolumeFormattedResponse(in, out)
}

func autoConvert_internal_IsVolumeFormattedResponse_To_v1beta3_IsVolumeFormattedResponse(in *internal.IsVolumeFormattedResponse, out *v1beta3.IsVolumeFormattedResponse) error {
	out.Formatted = in.Formatted
	return nil
}

// Convert_internal_IsVolumeFormattedResponse_To_v1beta3_IsVolumeFormattedResponse is an autogenerated conversion function.
func Convert_internal_IsVolumeFormattedResponse_To_v1beta3_IsVolumeFormattedResponse(in *internal.IsVolumeFormattedResponse, out *v1beta3.IsVolumeFormattedResponse) error {
	return autoConvert_internal_IsVolumeFormattedResponse_To_v1beta3_IsVolumeFormattedResponse(in, out)
}

func autoConvert_v1beta3_ListVolumesOnDiskRequest_To_internal_ListVolumesOnDiskRequest(in *v1beta3.ListVolumesOnDiskRequest, out *internal.ListVolumesOnDiskRequest) error {
	out.DiskNumber = in.DiskNumber
	out.PartitionNumber = in.PartitionNumber
	return nil
}

// Convert_v1beta3_ListVolumesOnDiskRequest_To_internal_ListVolumesOnDiskRequest is an autogenerated conversion function.
func Convert_v1beta3_ListVolumesOnDiskRequest_To_internal_ListVolumesOnDiskRequest(in *v1beta3.ListVolumesOnDiskRequest, out *internal.ListVolumesOnDiskRequest) error {
	return autoConvert_v1beta3_ListVolumesOnDiskRequest_To_internal_ListVolumesOnDiskRequest(in, out)
}

func autoConvert_internal_ListVolumesOnDiskRequest_To_v1beta3_ListVolumesOnDiskRequest(in *internal.ListVolumesOnDiskRequest, out *v1beta3.ListVolumesOnDiskRequest) error {
	out.DiskNumber = in.DiskNumber
	out.PartitionNumber = in.PartitionNumber
	return nil
}

// Convert_internal_ListVolumesOnDiskRequest_To_v1beta3_ListVolumesOnDiskRequest is an autogenerated conversion function.
func Convert_internal_ListVolumesOnDiskRequest_To_v1beta3_ListVolumesOnDiskRequest(in *internal.ListVolumesOnDiskRequest, out *v1beta3.ListVolumesOnDiskRequest) error {
	return autoConvert_internal_ListVolumesOnDiskRequest_To_v1beta3_ListVolumesOnDiskRequest(in, out)
}

func autoConvert_v1beta3_ListVolumesOnDiskResponse_To_internal_ListVolumesOnDiskResponse(in *v1beta3.ListVolumesOnDiskResponse, out *internal.ListVolumesOnDiskResponse) error {
	out.VolumeIds = *(*[]string)(unsafe.Pointer(&in.VolumeIds))
	return nil
}

// Convert_v1beta3_ListVolumesOnDiskResponse_To_internal_ListVolumesOnDiskResponse is an autogenerated conversion function.
func Convert_v1beta3_ListVolumesOnDiskResponse_To_internal_ListVolumesOnDiskResponse(in *v1beta3.ListVolumesOnDiskResponse, out *internal.ListVolumesOnDiskResponse) error {
	return autoConvert_v1beta3_ListVolumesOnDiskResponse_To_internal_ListVolumesOnDiskResponse(in, out)
}

func autoConvert_internal_ListVolumesOnDiskResponse_To_v1beta3_ListVolumesOnDiskResponse(in *internal.ListVolumesOnDiskResponse, out *v1beta3.ListVolumesOnDiskResponse) error {
	out.VolumeIds = *(*[]string)(unsafe.Pointer(&in.VolumeIds))
	return nil
}

// Convert_internal_ListVolumesOnDiskResponse_To_v1beta3_ListVolumesOnDiskResponse is an autogenerated conversion function.
func Convert_internal_ListVolumesOnDiskResponse_To_v1beta3_ListVolumesOnDiskResponse(in *internal.ListVolumesOnDiskResponse, out *v1beta3.ListVolumesOnDiskResponse) error {
	return autoConvert_internal_ListVolumesOnDiskResponse_To_v1beta3_ListVolumesOnDiskResponse(in, out)
}

func autoConvert_v1beta3_MountVolumeRequest_To_internal_MountVolumeRequest(in *v1beta3.MountVolumeRequest, out *internal.MountVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_v1beta3_MountVolumeRequest_To_internal_MountVolumeRequest is an autogenerated conversion function.
func Convert_v1beta3_MountVolumeRequest_To_internal_MountVolumeRequest(in *v1beta3.MountVolumeRequest, out *internal.MountVolumeRequest) error {
	return autoConvert_v1beta3_MountVolumeRequest_To_internal_MountVolumeRequest(in, out)
}

func autoConvert_internal_MountVolumeRequest_To_v1beta3_MountVolumeRequest(in *internal.MountVolumeRequest, out *v1beta3.MountVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_internal_MountVolumeRequest_To_v1beta3_MountVolumeRequest is an autogenerated conversion function.
func Convert_internal_MountVolumeRequest_To_v1beta3_MountVolumeRequest(in *internal.MountVolumeRequest, out *v1beta3.MountVolumeRequest) error {
	return autoConvert_internal_MountVolumeRequest_To_v1beta3_MountVolumeRequest(in, out)
}

func autoConvert_v1beta3_MountVolumeResponse_To_internal_MountVolumeResponse(in *v1beta3.MountVolumeResponse, out *internal.MountVolumeResponse) error {
	return nil
}

// Convert_v1beta3_MountVolumeResponse_To_internal_MountVolumeResponse is an autogenerated conversion function.
func Convert_v1beta3_MountVolumeResponse_To_internal_MountVolumeResponse(in *v1beta3.MountVolumeResponse, out *internal.MountVolumeResponse) error {
	return autoConvert_v1beta3_MountVolumeResponse_To_internal_MountVolumeResponse(in, out)
}

func autoConvert_internal_MountVolumeResponse_To_v1beta3_MountVolumeResponse(in *internal.MountVolumeResponse, out *v1beta3.MountVolumeResponse) error {
	return nil
}

// Convert_internal_MountVolumeResponse_To_v1beta3_MountVolumeResponse is an autogenerated conversion function.
func Convert_internal_MountVolumeResponse_To_v1beta3_MountVolumeResponse(in *internal.MountVolumeResponse, out *v1beta3.MountVolumeResponse) error {
	return autoConvert_internal_MountVolumeResponse_To_v1beta3_MountVolumeResponse(in, out)
}

func autoConvert_v1beta3_ResizeVolumeRequest_To_internal_ResizeVolumeRequest(in *v1beta3.ResizeVolumeRequest, out *internal.ResizeVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.SizeBytes = in.SizeBytes
	return nil
}

// Convert_v1beta3_ResizeVolumeRequest_To_internal_ResizeVolumeRequest is an autogenerated conversion function.
func Convert_v1beta3_ResizeVolumeRequest_To_internal_ResizeVolumeRequest(in *v1beta3.ResizeVolumeRequest, out *internal.ResizeVolumeRequest) error {
	return autoConvert_v1beta3_ResizeVolumeRequest_To_internal_ResizeVolumeRequest(in, out)
}

func autoConvert_internal_ResizeVolumeRequest_To_v1beta3_ResizeVolumeRequest(in *internal.ResizeVolumeRequest, out *v1beta3.ResizeVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.SizeBytes = in.SizeBytes
	return nil
}

// Convert_internal_ResizeVolumeRequest_To_v1beta3_ResizeVolumeRequest is an autogenerated conversion function.
func Convert_internal_ResizeVolumeRequest_To_v1beta3_ResizeVolumeRequest(in *internal.ResizeVolumeRequest, out *v1beta3.ResizeVolumeRequest) error {
	return autoConvert_internal_ResizeVolumeRequest_To_v1beta3_ResizeVolumeRequest(in, out)
}

func autoConvert_v1beta3_ResizeVolumeResponse_To_internal_ResizeVolumeResponse(in *v1beta3.ResizeVolumeResponse, out *internal.ResizeVolumeResponse) error {
	return nil
}

// Convert_v1beta3_ResizeVolumeResponse_To_internal_ResizeVolumeResponse is an autogenerated conversion function.
func Convert_v1beta3_ResizeVolumeResponse_To_internal_ResizeVolumeResponse(in *v1beta3.ResizeVolumeResponse, out *internal.ResizeVolumeResponse) error {
	return autoConvert_v1beta3_ResizeVolumeResponse_To_internal_ResizeVolumeResponse(in, out)
}

func autoConvert_internal_ResizeVolumeResponse_To_v1beta3_ResizeVolumeResponse(in *internal.ResizeVolumeResponse, out *v1beta3.ResizeVolumeResponse) error {
	return nil
}

// Convert_internal_ResizeVolumeResponse_To_v1beta3_ResizeVolumeResponse is an autogenerated conversion function.
func Convert_internal_ResizeVolumeResponse_To_v1beta3_ResizeVolumeResponse(in *internal.ResizeVolumeResponse, out *v1beta3.ResizeVolumeResponse) error {
	return autoConvert_internal_ResizeVolumeResponse_To_v1beta3_ResizeVolumeResponse(in, out)
}

func autoConvert_v1beta3_UnmountVolumeRequest_To_internal_UnmountVolumeRequest(in *v1beta3.UnmountVolumeRequest, out *internal.UnmountVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_v1beta3_UnmountVolumeRequest_To_internal_UnmountVolumeRequest is an autogenerated conversion function.
func Convert_v1beta3_UnmountVolumeRequest_To_internal_UnmountVolumeRequest(in *v1beta3.UnmountVolumeRequest, out *internal.UnmountVolumeRequest) error {
	return autoConvert_v1beta3_UnmountVolumeRequest_To_internal_UnmountVolumeRequest(in, out)
}

func autoConvert_internal_UnmountVolumeRequest_To_v1beta3_UnmountVolumeRequest(in *internal.UnmountVolumeRequest, out *v1beta3.UnmountVolumeRequest) error {
	out.VolumeId = in.VolumeId
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_internal_UnmountVolumeRequest_To_v1beta3_UnmountVolumeRequest is an autogenerated conversion function.
func Convert_internal_UnmountVolumeRequest_To_v1beta3_UnmountVolumeRequest(in *internal.UnmountVolumeRequest, out *v1beta3.UnmountVolumeRequest) error {
	return autoConvert_internal_UnmountVolumeRequest_To_v1beta3_UnmountVolumeRequest(in, out)
}

func autoConvert_v1beta3_UnmountVolumeResponse_To_internal_UnmountVolumeResponse(in *v1beta3.UnmountVolumeResponse, out *internal.UnmountVolumeResponse) error {
	return nil
}

// Convert_v1beta3_UnmountVolumeResponse_To_internal_UnmountVolumeResponse is an autogenerated conversion function.
func Convert_v1beta3_UnmountVolumeResponse_To_internal_UnmountVolumeResponse(in *v1beta3.UnmountVolumeResponse, out *internal.UnmountVolumeResponse) error {
	return autoConvert_v1beta3_UnmountVolumeResponse_To_internal_UnmountVolumeResponse(in, out)
}

func autoConvert_internal_UnmountVolumeResponse_To_v1beta3_UnmountVolumeResponse(in *internal.UnmountVolumeResponse, out *v1beta3.UnmountVolumeResponse) error {
	return nil
}

// Convert_internal_UnmountVolumeResponse_To_v1beta3_UnmountVolumeResponse is an autogenerated conversion function.
func Convert_internal_UnmountVolumeResponse_To_v1beta3_UnmountVolumeResponse(in *internal.UnmountVolumeResponse, out *v1beta3.UnmountVolumeResponse) error {
	return autoConvert_internal_UnmountVolumeResponse_To_v1beta3_UnmountVolumeResponse(in, out)
}

func autoConvert_v1beta3_WriteVolumeCacheRequest_To_internal_WriteVolumeCacheRequest(in *v1beta3.WriteVolumeCacheRequest, out *internal.WriteVolumeCacheRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_v1beta3_WriteVolumeCacheRequest_To_internal_WriteVolumeCacheRequest is an autogenerated conversion function.
func Convert_v1beta3_WriteVolumeCacheRequest_To_internal_WriteVolumeCacheRequest(in *v1beta3.WriteVolumeCacheRequest, out *internal.WriteVolumeCacheRequest) error {
	return autoConvert_v1beta3_WriteVolumeCacheRequest_To_internal_WriteVolumeCacheRequest(in, out)
}

func autoConvert_internal_WriteVolumeCacheRequest_To_v1beta3_WriteVolumeCacheRequest(in *internal.WriteVolumeCacheRequest, out *v1beta3.WriteVolumeCacheRequest) error {
	out.VolumeId = in.VolumeId
	return nil
}

// Convert_internal_WriteVolumeCacheRequest_To_v1beta3_WriteVolumeCacheRequest is an autogenerated conversion function.
func Convert_internal_WriteVolumeCacheRequest_To_v1beta3_WriteVolumeCacheRequest(in *internal.WriteVolumeCacheRequest, out *v1beta3.WriteVolumeCacheRequest) error {
	return autoConvert_internal_WriteVolumeCacheRequest_To_v1beta3_WriteVolumeCacheRequest(in, out)
}

func autoConvert_v1beta3_WriteVolumeCacheResponse_To_internal_WriteVolumeCacheResponse(in *v1beta3.WriteVolumeCacheResponse, out *internal.WriteVolumeCacheResponse) error {
	return nil
}

// Convert_v1beta3_WriteVolumeCacheResponse_To_internal_WriteVolumeCacheResponse is an autogenerated conversion function.
func Convert_v1beta3_WriteVolumeCacheResponse_To_internal_WriteVolumeCacheResponse(in *v1beta3.WriteVolumeCacheResponse, out *internal.WriteVolumeCacheResponse) error {
	return autoConvert_v1beta3_WriteVolumeCacheResponse_To_internal_WriteVolumeCacheResponse(in, out)
}

func autoConvert_internal_WriteVolumeCacheResponse_To_v1beta3_WriteVolumeCacheResponse(in *internal.WriteVolumeCacheResponse, out *v1beta3.WriteVolumeCacheResponse) error {
	return nil
}

// Convert_internal_WriteVolumeCacheResponse_To_v1beta3_WriteVolumeCacheResponse is an autogenerated conversion function.
func Convert_internal_WriteVolumeCacheResponse_To_v1beta3_WriteVolumeCacheResponse(in *internal.WriteVolumeCacheResponse, out *v1beta3.WriteVolumeCacheResponse) error {
	return autoConvert_internal_WriteVolumeCacheResponse_To_v1beta3_WriteVolumeCacheResponse(in, out)
}
