// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1beta3

import (
	v1beta3 "github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta3"
	impl "github.com/kubernetes-csi/csi-proxy/pkg/server/disk/impl"
)

func autoConvert_v1beta3_DiskIDs_To_impl_DiskIDs(in *v1beta3.DiskIDs, out *impl.DiskIDs) error {
	out.Page83 = in.Page83
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_v1beta3_DiskIDs_To_impl_DiskIDs is an autogenerated conversion function.
func Convert_v1beta3_DiskIDs_To_impl_DiskIDs(in *v1beta3.DiskIDs, out *impl.DiskIDs) error {
	return autoConvert_v1beta3_DiskIDs_To_impl_DiskIDs(in, out)
}

func autoConvert_impl_DiskIDs_To_v1beta3_DiskIDs(in *impl.DiskIDs, out *v1beta3.DiskIDs) error {
	out.Page83 = in.Page83
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_impl_DiskIDs_To_v1beta3_DiskIDs is an autogenerated conversion function.
func Convert_impl_DiskIDs_To_v1beta3_DiskIDs(in *impl.DiskIDs, out *v1beta3.DiskIDs) error {
	return autoConvert_impl_DiskIDs_To_v1beta3_DiskIDs(in, out)
}

func autoConvert_v1beta3_DiskLocation_To_impl_DiskLocation(in *v1beta3.DiskLocation, out *impl.DiskLocation) error {
	out.Adapter = in.Adapter
	out.Bus = in.Bus
	out.Target = in.Target
	out.LUNID = in.LUNID
	return nil
}

// Convert_v1beta3_DiskLocation_To_impl_DiskLocation is an autogenerated conversion function.
func Convert_v1beta3_DiskLocation_To_impl_DiskLocation(in *v1beta3.DiskLocation, out *impl.DiskLocation) error {
	return autoConvert_v1beta3_DiskLocation_To_impl_DiskLocation(in, out)
}

func autoConvert_impl_DiskLocation_To_v1beta3_DiskLocation(in *impl.DiskLocation, out *v1beta3.DiskLocation) error {
	out.Adapter = in.Adapter
	out.Bus = in.Bus
	out.Target = in.Target
	out.LUNID = in.LUNID
	return nil
}

// Convert_impl_DiskLocation_To_v1beta3_DiskLocation is an autogenerated conversion function.
func Convert_impl_DiskLocation_To_v1beta3_DiskLocation(in *impl.DiskLocation, out *v1beta3.DiskLocation) error {
	return autoConvert_impl_DiskLocation_To_v1beta3_DiskLocation(in, out)
}

func autoConvert_v1beta3_GetDiskStateRequest_To_impl_GetDiskStateRequest(in *v1beta3.GetDiskStateRequest, out *impl.GetDiskStateRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_v1beta3_GetDiskStateRequest_To_impl_GetDiskStateRequest is an autogenerated conversion function.
func Convert_v1beta3_GetDiskStateRequest_To_impl_GetDiskStateRequest(in *v1beta3.GetDiskStateRequest, out *impl.GetDiskStateRequest) error {
	return autoConvert_v1beta3_GetDiskStateRequest_To_impl_GetDiskStateRequest(in, out)
}

func autoConvert_impl_GetDiskStateRequest_To_v1beta3_GetDiskStateRequest(in *impl.GetDiskStateRequest, out *v1beta3.GetDiskStateRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_impl_GetDiskStateRequest_To_v1beta3_GetDiskStateRequest is an autogenerated conversion function.
func Convert_impl_GetDiskStateRequest_To_v1beta3_GetDiskStateRequest(in *impl.GetDiskStateRequest, out *v1beta3.GetDiskStateRequest) error {
	return autoConvert_impl_GetDiskStateRequest_To_v1beta3_GetDiskStateRequest(in, out)
}

func autoConvert_v1beta3_GetDiskStateResponse_To_impl_GetDiskStateResponse(in *v1beta3.GetDiskStateResponse, out *impl.GetDiskStateResponse) error {
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_v1beta3_GetDiskStateResponse_To_impl_GetDiskStateResponse is an autogenerated conversion function.
func Convert_v1beta3_GetDiskStateResponse_To_impl_GetDiskStateResponse(in *v1beta3.GetDiskStateResponse, out *impl.GetDiskStateResponse) error {
	return autoConvert_v1beta3_GetDiskStateResponse_To_impl_GetDiskStateResponse(in, out)
}

func autoConvert_impl_GetDiskStateResponse_To_v1beta3_GetDiskStateResponse(in *impl.GetDiskStateResponse, out *v1beta3.GetDiskStateResponse) error {
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_impl_GetDiskStateResponse_To_v1beta3_GetDiskStateResponse is an autogenerated conversion function.
func Convert_impl_GetDiskStateResponse_To_v1beta3_GetDiskStateResponse(in *impl.GetDiskStateResponse, out *v1beta3.GetDiskStateResponse) error {
	return autoConvert_impl_GetDiskStateResponse_To_v1beta3_GetDiskStateResponse(in, out)
}

func autoConvert_v1beta3_GetDiskStatsRequest_To_impl_GetDiskStatsRequest(in *v1beta3.GetDiskStatsRequest, out *impl.GetDiskStatsRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_v1beta3_GetDiskStatsRequest_To_impl_GetDiskStatsRequest is an autogenerated conversion function.
func Convert_v1beta3_GetDiskStatsRequest_To_impl_GetDiskStatsRequest(in *v1beta3.GetDiskStatsRequest, out *impl.GetDiskStatsRequest) error {
	return autoConvert_v1beta3_GetDiskStatsRequest_To_impl_GetDiskStatsRequest(in, out)
}

func autoConvert_impl_GetDiskStatsRequest_To_v1beta3_GetDiskStatsRequest(in *impl.GetDiskStatsRequest, out *v1beta3.GetDiskStatsRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_impl_GetDiskStatsRequest_To_v1beta3_GetDiskStatsRequest is an autogenerated conversion function.
func Convert_impl_GetDiskStatsRequest_To_v1beta3_GetDiskStatsRequest(in *impl.GetDiskStatsRequest, out *v1beta3.GetDiskStatsRequest) error {
	return autoConvert_impl_GetDiskStatsRequest_To_v1beta3_GetDiskStatsRequest(in, out)
}

func autoConvert_v1beta3_GetDiskStatsResponse_To_impl_GetDiskStatsResponse(in *v1beta3.GetDiskStatsResponse, out *impl.GetDiskStatsResponse) error {
	out.TotalBytes = in.TotalBytes
	return nil
}

// Convert_v1beta3_GetDiskStatsResponse_To_impl_GetDiskStatsResponse is an autogenerated conversion function.
func Convert_v1beta3_GetDiskStatsResponse_To_impl_GetDiskStatsResponse(in *v1beta3.GetDiskStatsResponse, out *impl.GetDiskStatsResponse) error {
	return autoConvert_v1beta3_GetDiskStatsResponse_To_impl_GetDiskStatsResponse(in, out)
}

func autoConvert_impl_GetDiskStatsResponse_To_v1beta3_GetDiskStatsResponse(in *impl.GetDiskStatsResponse, out *v1beta3.GetDiskStatsResponse) error {
	out.TotalBytes = in.TotalBytes
	return nil
}

// Convert_impl_GetDiskStatsResponse_To_v1beta3_GetDiskStatsResponse is an autogenerated conversion function.
func Convert_impl_GetDiskStatsResponse_To_v1beta3_GetDiskStatsResponse(in *impl.GetDiskStatsResponse, out *v1beta3.GetDiskStatsResponse) error {
	return autoConvert_impl_GetDiskStatsResponse_To_v1beta3_GetDiskStatsResponse(in, out)
}

func autoConvert_v1beta3_ListDiskIDsRequest_To_impl_ListDiskIDsRequest(in *v1beta3.ListDiskIDsRequest, out *impl.ListDiskIDsRequest) error {
	return nil
}

// Convert_v1beta3_ListDiskIDsRequest_To_impl_ListDiskIDsRequest is an autogenerated conversion function.
func Convert_v1beta3_ListDiskIDsRequest_To_impl_ListDiskIDsRequest(in *v1beta3.ListDiskIDsRequest, out *impl.ListDiskIDsRequest) error {
	return autoConvert_v1beta3_ListDiskIDsRequest_To_impl_ListDiskIDsRequest(in, out)
}

func autoConvert_impl_ListDiskIDsRequest_To_v1beta3_ListDiskIDsRequest(in *impl.ListDiskIDsRequest, out *v1beta3.ListDiskIDsRequest) error {
	return nil
}

// Convert_impl_ListDiskIDsRequest_To_v1beta3_ListDiskIDsRequest is an autogenerated conversion function.
func Convert_impl_ListDiskIDsRequest_To_v1beta3_ListDiskIDsRequest(in *impl.ListDiskIDsRequest, out *v1beta3.ListDiskIDsRequest) error {
	return autoConvert_impl_ListDiskIDsRequest_To_v1beta3_ListDiskIDsRequest(in, out)
}

func autoConvert_v1beta3_ListDiskIDsResponse_To_impl_ListDiskIDsResponse(in *v1beta3.ListDiskIDsResponse, out *impl.ListDiskIDsResponse) error {
	if in.DiskIDs != nil {
		in, out := &in.DiskIDs, &out.DiskIDs
		*out = make(map[uint32]*impl.DiskIDs, len(*in))
		for key, val := range *in {
			newVal := new(*impl.DiskIDs)
			if err := Convert_v1beta3_DiskIDs_To_impl_DiskIDs(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskIDs = nil
	}
	return nil
}

// Convert_v1beta3_ListDiskIDsResponse_To_impl_ListDiskIDsResponse is an autogenerated conversion function.
func Convert_v1beta3_ListDiskIDsResponse_To_impl_ListDiskIDsResponse(in *v1beta3.ListDiskIDsResponse, out *impl.ListDiskIDsResponse) error {
	return autoConvert_v1beta3_ListDiskIDsResponse_To_impl_ListDiskIDsResponse(in, out)
}

// detected external conversion function
// Convert_impl_ListDiskIDsResponse_To_v1beta3_ListDiskIDsResponse(in *impl.ListDiskIDsResponse, out *v1beta3.ListDiskIDsResponse) error
// skipping generation of the auto function

func autoConvert_v1beta3_ListDiskLocationsRequest_To_impl_ListDiskLocationsRequest(in *v1beta3.ListDiskLocationsRequest, out *impl.ListDiskLocationsRequest) error {
	return nil
}

// Convert_v1beta3_ListDiskLocationsRequest_To_impl_ListDiskLocationsRequest is an autogenerated conversion function.
func Convert_v1beta3_ListDiskLocationsRequest_To_impl_ListDiskLocationsRequest(in *v1beta3.ListDiskLocationsRequest, out *impl.ListDiskLocationsRequest) error {
	return autoConvert_v1beta3_ListDiskLocationsRequest_To_impl_ListDiskLocationsRequest(in, out)
}

func autoConvert_impl_ListDiskLocationsRequest_To_v1beta3_ListDiskLocationsRequest(in *impl.ListDiskLocationsRequest, out *v1beta3.ListDiskLocationsRequest) error {
	return nil
}

// Convert_impl_ListDiskLocationsRequest_To_v1beta3_ListDiskLocationsRequest is an autogenerated conversion function.
func Convert_impl_ListDiskLocationsRequest_To_v1beta3_ListDiskLocationsRequest(in *impl.ListDiskLocationsRequest, out *v1beta3.ListDiskLocationsRequest) error {
	return autoConvert_impl_ListDiskLocationsRequest_To_v1beta3_ListDiskLocationsRequest(in, out)
}

func autoConvert_v1beta3_ListDiskLocationsResponse_To_impl_ListDiskLocationsResponse(in *v1beta3.ListDiskLocationsResponse, out *impl.ListDiskLocationsResponse) error {
	if in.DiskLocations != nil {
		in, out := &in.DiskLocations, &out.DiskLocations
		*out = make(map[uint32]*impl.DiskLocation, len(*in))
		for key, val := range *in {
			newVal := new(*impl.DiskLocation)
			if err := Convert_v1beta3_DiskLocation_To_impl_DiskLocation(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskLocations = nil
	}
	return nil
}

// Convert_v1beta3_ListDiskLocationsResponse_To_impl_ListDiskLocationsResponse is an autogenerated conversion function.
func Convert_v1beta3_ListDiskLocationsResponse_To_impl_ListDiskLocationsResponse(in *v1beta3.ListDiskLocationsResponse, out *impl.ListDiskLocationsResponse) error {
	return autoConvert_v1beta3_ListDiskLocationsResponse_To_impl_ListDiskLocationsResponse(in, out)
}

// detected external conversion function
// Convert_impl_ListDiskLocationsResponse_To_v1beta3_ListDiskLocationsResponse(in *impl.ListDiskLocationsResponse, out *v1beta3.ListDiskLocationsResponse) error
// skipping generation of the auto function

func autoConvert_v1beta3_PartitionDiskRequest_To_impl_PartitionDiskRequest(in *v1beta3.PartitionDiskRequest, out *impl.PartitionDiskRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_v1beta3_PartitionDiskRequest_To_impl_PartitionDiskRequest is an autogenerated conversion function.
func Convert_v1beta3_PartitionDiskRequest_To_impl_PartitionDiskRequest(in *v1beta3.PartitionDiskRequest, out *impl.PartitionDiskRequest) error {
	return autoConvert_v1beta3_PartitionDiskRequest_To_impl_PartitionDiskRequest(in, out)
}

func autoConvert_impl_PartitionDiskRequest_To_v1beta3_PartitionDiskRequest(in *impl.PartitionDiskRequest, out *v1beta3.PartitionDiskRequest) error {
	out.DiskNumber = in.DiskNumber
	return nil
}

// Convert_impl_PartitionDiskRequest_To_v1beta3_PartitionDiskRequest is an autogenerated conversion function.
func Convert_impl_PartitionDiskRequest_To_v1beta3_PartitionDiskRequest(in *impl.PartitionDiskRequest, out *v1beta3.PartitionDiskRequest) error {
	return autoConvert_impl_PartitionDiskRequest_To_v1beta3_PartitionDiskRequest(in, out)
}

func autoConvert_v1beta3_PartitionDiskResponse_To_impl_PartitionDiskResponse(in *v1beta3.PartitionDiskResponse, out *impl.PartitionDiskResponse) error {
	return nil
}

// Convert_v1beta3_PartitionDiskResponse_To_impl_PartitionDiskResponse is an autogenerated conversion function.
func Convert_v1beta3_PartitionDiskResponse_To_impl_PartitionDiskResponse(in *v1beta3.PartitionDiskResponse, out *impl.PartitionDiskResponse) error {
	return autoConvert_v1beta3_PartitionDiskResponse_To_impl_PartitionDiskResponse(in, out)
}

func autoConvert_impl_PartitionDiskResponse_To_v1beta3_PartitionDiskResponse(in *impl.PartitionDiskResponse, out *v1beta3.PartitionDiskResponse) error {
	return nil
}

// Convert_impl_PartitionDiskResponse_To_v1beta3_PartitionDiskResponse is an autogenerated conversion function.
func Convert_impl_PartitionDiskResponse_To_v1beta3_PartitionDiskResponse(in *impl.PartitionDiskResponse, out *v1beta3.PartitionDiskResponse) error {
	return autoConvert_impl_PartitionDiskResponse_To_v1beta3_PartitionDiskResponse(in, out)
}

func autoConvert_v1beta3_RescanRequest_To_impl_RescanRequest(in *v1beta3.RescanRequest, out *impl.RescanRequest) error {
	return nil
}

// Convert_v1beta3_RescanRequest_To_impl_RescanRequest is an autogenerated conversion function.
func Convert_v1beta3_RescanRequest_To_impl_RescanRequest(in *v1beta3.RescanRequest, out *impl.RescanRequest) error {
	return autoConvert_v1beta3_RescanRequest_To_impl_RescanRequest(in, out)
}

func autoConvert_impl_RescanRequest_To_v1beta3_RescanRequest(in *impl.RescanRequest, out *v1beta3.RescanRequest) error {
	return nil
}

// Convert_impl_RescanRequest_To_v1beta3_RescanRequest is an autogenerated conversion function.
func Convert_impl_RescanRequest_To_v1beta3_RescanRequest(in *impl.RescanRequest, out *v1beta3.RescanRequest) error {
	return autoConvert_impl_RescanRequest_To_v1beta3_RescanRequest(in, out)
}

func autoConvert_v1beta3_RescanResponse_To_impl_RescanResponse(in *v1beta3.RescanResponse, out *impl.RescanResponse) error {
	return nil
}

// Convert_v1beta3_RescanResponse_To_impl_RescanResponse is an autogenerated conversion function.
func Convert_v1beta3_RescanResponse_To_impl_RescanResponse(in *v1beta3.RescanResponse, out *impl.RescanResponse) error {
	return autoConvert_v1beta3_RescanResponse_To_impl_RescanResponse(in, out)
}

func autoConvert_impl_RescanResponse_To_v1beta3_RescanResponse(in *impl.RescanResponse, out *v1beta3.RescanResponse) error {
	return nil
}

// Convert_impl_RescanResponse_To_v1beta3_RescanResponse is an autogenerated conversion function.
func Convert_impl_RescanResponse_To_v1beta3_RescanResponse(in *impl.RescanResponse, out *v1beta3.RescanResponse) error {
	return autoConvert_impl_RescanResponse_To_v1beta3_RescanResponse(in, out)
}

func autoConvert_v1beta3_SetDiskStateRequest_To_impl_SetDiskStateRequest(in *v1beta3.SetDiskStateRequest, out *impl.SetDiskStateRequest) error {
	out.DiskNumber = in.DiskNumber
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_v1beta3_SetDiskStateRequest_To_impl_SetDiskStateRequest is an autogenerated conversion function.
func Convert_v1beta3_SetDiskStateRequest_To_impl_SetDiskStateRequest(in *v1beta3.SetDiskStateRequest, out *impl.SetDiskStateRequest) error {
	return autoConvert_v1beta3_SetDiskStateRequest_To_impl_SetDiskStateRequest(in, out)
}

func autoConvert_impl_SetDiskStateRequest_To_v1beta3_SetDiskStateRequest(in *impl.SetDiskStateRequest, out *v1beta3.SetDiskStateRequest) error {
	out.DiskNumber = in.DiskNumber
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_impl_SetDiskStateRequest_To_v1beta3_SetDiskStateRequest is an autogenerated conversion function.
func Convert_impl_SetDiskStateRequest_To_v1beta3_SetDiskStateRequest(in *impl.SetDiskStateRequest, out *v1beta3.SetDiskStateRequest) error {
	return autoConvert_impl_SetDiskStateRequest_To_v1beta3_SetDiskStateRequest(in, out)
}

func autoConvert_v1beta3_SetDiskStateResponse_To_impl_SetDiskStateResponse(in *v1beta3.SetDiskStateResponse, out *impl.SetDiskStateResponse) error {
	return nil
}

// Convert_v1beta3_SetDiskStateResponse_To_impl_SetDiskStateResponse is an autogenerated conversion function.
func Convert_v1beta3_SetDiskStateResponse_To_impl_SetDiskStateResponse(in *v1beta3.SetDiskStateResponse, out *impl.SetDiskStateResponse) error {
	return autoConvert_v1beta3_SetDiskStateResponse_To_impl_SetDiskStateResponse(in, out)
}

func autoConvert_impl_SetDiskStateResponse_To_v1beta3_SetDiskStateResponse(in *impl.SetDiskStateResponse, out *v1beta3.SetDiskStateResponse) error {
	return nil
}

// Convert_impl_SetDiskStateResponse_To_v1beta3_SetDiskStateResponse is an autogenerated conversion function.
func Convert_impl_SetDiskStateResponse_To_v1beta3_SetDiskStateResponse(in *impl.SetDiskStateResponse, out *v1beta3.SetDiskStateResponse) error {
	return autoConvert_impl_SetDiskStateResponse_To_v1beta3_SetDiskStateResponse(in, out)
}
