// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1"
	internal "github.com/kubernetes-csi/csi-proxy/internal/server/system/internal"
)

func autoConvert_v1alpha1_GetBIOSSerialNumberRequest_To_internal_GetBIOSSerialNumberRequest(in *v1alpha1.GetBIOSSerialNumberRequest, out *internal.GetBIOSSerialNumberRequest) error {
	return nil
}

// Convert_v1alpha1_GetBIOSSerialNumberRequest_To_internal_GetBIOSSerialNumberRequest is an autogenerated conversion function.
func Convert_v1alpha1_GetBIOSSerialNumberRequest_To_internal_GetBIOSSerialNumberRequest(in *v1alpha1.GetBIOSSerialNumberRequest, out *internal.GetBIOSSerialNumberRequest) error {
	return autoConvert_v1alpha1_GetBIOSSerialNumberRequest_To_internal_GetBIOSSerialNumberRequest(in, out)
}

func autoConvert_internal_GetBIOSSerialNumberRequest_To_v1alpha1_GetBIOSSerialNumberRequest(in *internal.GetBIOSSerialNumberRequest, out *v1alpha1.GetBIOSSerialNumberRequest) error {
	return nil
}

// Convert_internal_GetBIOSSerialNumberRequest_To_v1alpha1_GetBIOSSerialNumberRequest is an autogenerated conversion function.
func Convert_internal_GetBIOSSerialNumberRequest_To_v1alpha1_GetBIOSSerialNumberRequest(in *internal.GetBIOSSerialNumberRequest, out *v1alpha1.GetBIOSSerialNumberRequest) error {
	return autoConvert_internal_GetBIOSSerialNumberRequest_To_v1alpha1_GetBIOSSerialNumberRequest(in, out)
}

func autoConvert_v1alpha1_GetBIOSSerialNumberResponse_To_internal_GetBIOSSerialNumberResponse(in *v1alpha1.GetBIOSSerialNumberResponse, out *internal.GetBIOSSerialNumberResponse) error {
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_v1alpha1_GetBIOSSerialNumberResponse_To_internal_GetBIOSSerialNumberResponse is an autogenerated conversion function.
func Convert_v1alpha1_GetBIOSSerialNumberResponse_To_internal_GetBIOSSerialNumberResponse(in *v1alpha1.GetBIOSSerialNumberResponse, out *internal.GetBIOSSerialNumberResponse) error {
	return autoConvert_v1alpha1_GetBIOSSerialNumberResponse_To_internal_GetBIOSSerialNumberResponse(in, out)
}

func autoConvert_internal_GetBIOSSerialNumberResponse_To_v1alpha1_GetBIOSSerialNumberResponse(in *internal.GetBIOSSerialNumberResponse, out *v1alpha1.GetBIOSSerialNumberResponse) error {
	out.SerialNumber = in.SerialNumber
	return nil
}

// Convert_internal_GetBIOSSerialNumberResponse_To_v1alpha1_GetBIOSSerialNumberResponse is an autogenerated conversion function.
func Convert_internal_GetBIOSSerialNumberResponse_To_v1alpha1_GetBIOSSerialNumberResponse(in *internal.GetBIOSSerialNumberResponse, out *v1alpha1.GetBIOSSerialNumberResponse) error {
	return autoConvert_internal_GetBIOSSerialNumberResponse_To_v1alpha1_GetBIOSSerialNumberResponse(in, out)
}

func autoConvert_v1alpha1_GetServiceRequest_To_internal_GetServiceRequest(in *v1alpha1.GetServiceRequest, out *internal.GetServiceRequest) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_GetServiceRequest_To_internal_GetServiceRequest is an autogenerated conversion function.
func Convert_v1alpha1_GetServiceRequest_To_internal_GetServiceRequest(in *v1alpha1.GetServiceRequest, out *internal.GetServiceRequest) error {
	return autoConvert_v1alpha1_GetServiceRequest_To_internal_GetServiceRequest(in, out)
}

func autoConvert_internal_GetServiceRequest_To_v1alpha1_GetServiceRequest(in *internal.GetServiceRequest, out *v1alpha1.GetServiceRequest) error {
	out.Name = in.Name
	return nil
}

// Convert_internal_GetServiceRequest_To_v1alpha1_GetServiceRequest is an autogenerated conversion function.
func Convert_internal_GetServiceRequest_To_v1alpha1_GetServiceRequest(in *internal.GetServiceRequest, out *v1alpha1.GetServiceRequest) error {
	return autoConvert_internal_GetServiceRequest_To_v1alpha1_GetServiceRequest(in, out)
}

func autoConvert_v1alpha1_GetServiceResponse_To_internal_GetServiceResponse(in *v1alpha1.GetServiceResponse, out *internal.GetServiceResponse) error {
	out.DisplayName = in.DisplayName
	out.StartType = internal.Startype(in.StartType)
	out.Status = internal.ServiceStatus(in.Status)
	return nil
}

// Convert_v1alpha1_GetServiceResponse_To_internal_GetServiceResponse is an autogenerated conversion function.
func Convert_v1alpha1_GetServiceResponse_To_internal_GetServiceResponse(in *v1alpha1.GetServiceResponse, out *internal.GetServiceResponse) error {
	return autoConvert_v1alpha1_GetServiceResponse_To_internal_GetServiceResponse(in, out)
}

func autoConvert_internal_GetServiceResponse_To_v1alpha1_GetServiceResponse(in *internal.GetServiceResponse, out *v1alpha1.GetServiceResponse) error {
	out.DisplayName = in.DisplayName
	out.StartType = v1alpha1.StartType(in.StartType)
	out.Status = v1alpha1.ServiceStatus(in.Status)
	return nil
}

// Convert_internal_GetServiceResponse_To_v1alpha1_GetServiceResponse is an autogenerated conversion function.
func Convert_internal_GetServiceResponse_To_v1alpha1_GetServiceResponse(in *internal.GetServiceResponse, out *v1alpha1.GetServiceResponse) error {
	return autoConvert_internal_GetServiceResponse_To_v1alpha1_GetServiceResponse(in, out)
}

func autoConvert_v1alpha1_StartServiceRequest_To_internal_StartServiceRequest(in *v1alpha1.StartServiceRequest, out *internal.StartServiceRequest) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_StartServiceRequest_To_internal_StartServiceRequest is an autogenerated conversion function.
func Convert_v1alpha1_StartServiceRequest_To_internal_StartServiceRequest(in *v1alpha1.StartServiceRequest, out *internal.StartServiceRequest) error {
	return autoConvert_v1alpha1_StartServiceRequest_To_internal_StartServiceRequest(in, out)
}

func autoConvert_internal_StartServiceRequest_To_v1alpha1_StartServiceRequest(in *internal.StartServiceRequest, out *v1alpha1.StartServiceRequest) error {
	out.Name = in.Name
	return nil
}

// Convert_internal_StartServiceRequest_To_v1alpha1_StartServiceRequest is an autogenerated conversion function.
func Convert_internal_StartServiceRequest_To_v1alpha1_StartServiceRequest(in *internal.StartServiceRequest, out *v1alpha1.StartServiceRequest) error {
	return autoConvert_internal_StartServiceRequest_To_v1alpha1_StartServiceRequest(in, out)
}

func autoConvert_v1alpha1_StartServiceResponse_To_internal_StartServiceResponse(in *v1alpha1.StartServiceResponse, out *internal.StartServiceResponse) error {
	return nil
}

// Convert_v1alpha1_StartServiceResponse_To_internal_StartServiceResponse is an autogenerated conversion function.
func Convert_v1alpha1_StartServiceResponse_To_internal_StartServiceResponse(in *v1alpha1.StartServiceResponse, out *internal.StartServiceResponse) error {
	return autoConvert_v1alpha1_StartServiceResponse_To_internal_StartServiceResponse(in, out)
}

func autoConvert_internal_StartServiceResponse_To_v1alpha1_StartServiceResponse(in *internal.StartServiceResponse, out *v1alpha1.StartServiceResponse) error {
	return nil
}

// Convert_internal_StartServiceResponse_To_v1alpha1_StartServiceResponse is an autogenerated conversion function.
func Convert_internal_StartServiceResponse_To_v1alpha1_StartServiceResponse(in *internal.StartServiceResponse, out *v1alpha1.StartServiceResponse) error {
	return autoConvert_internal_StartServiceResponse_To_v1alpha1_StartServiceResponse(in, out)
}

func autoConvert_v1alpha1_StopServiceRequest_To_internal_StopServiceRequest(in *v1alpha1.StopServiceRequest, out *internal.StopServiceRequest) error {
	out.Name = in.Name
	out.Force = in.Force
	return nil
}

// Convert_v1alpha1_StopServiceRequest_To_internal_StopServiceRequest is an autogenerated conversion function.
func Convert_v1alpha1_StopServiceRequest_To_internal_StopServiceRequest(in *v1alpha1.StopServiceRequest, out *internal.StopServiceRequest) error {
	return autoConvert_v1alpha1_StopServiceRequest_To_internal_StopServiceRequest(in, out)
}

func autoConvert_internal_StopServiceRequest_To_v1alpha1_StopServiceRequest(in *internal.StopServiceRequest, out *v1alpha1.StopServiceRequest) error {
	out.Name = in.Name
	out.Force = in.Force
	return nil
}

// Convert_internal_StopServiceRequest_To_v1alpha1_StopServiceRequest is an autogenerated conversion function.
func Convert_internal_StopServiceRequest_To_v1alpha1_StopServiceRequest(in *internal.StopServiceRequest, out *v1alpha1.StopServiceRequest) error {
	return autoConvert_internal_StopServiceRequest_To_v1alpha1_StopServiceRequest(in, out)
}

func autoConvert_v1alpha1_StopServiceResponse_To_internal_StopServiceResponse(in *v1alpha1.StopServiceResponse, out *internal.StopServiceResponse) error {
	return nil
}

// Convert_v1alpha1_StopServiceResponse_To_internal_StopServiceResponse is an autogenerated conversion function.
func Convert_v1alpha1_StopServiceResponse_To_internal_StopServiceResponse(in *v1alpha1.StopServiceResponse, out *internal.StopServiceResponse) error {
	return autoConvert_v1alpha1_StopServiceResponse_To_internal_StopServiceResponse(in, out)
}

func autoConvert_internal_StopServiceResponse_To_v1alpha1_StopServiceResponse(in *internal.StopServiceResponse, out *v1alpha1.StopServiceResponse) error {
	return nil
}

// Convert_internal_StopServiceResponse_To_v1alpha1_StopServiceResponse is an autogenerated conversion function.
func Convert_internal_StopServiceResponse_To_v1alpha1_StopServiceResponse(in *internal.StopServiceResponse, out *v1alpha1.StopServiceResponse) error {
	return autoConvert_internal_StopServiceResponse_To_v1alpha1_StopServiceResponse(in, out)
}
