// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package internal

import (
	"context"

	"github.com/kubernetes-csi/csi-proxy/client/apiversion"
	"google.golang.org/grpc"
)

type VersionedAPI interface {
	Register(grpcServer *grpc.Server)
}

// All the functions this group's server needs to define.
type ServerInterface interface {
	DiskStats(context.Context, *DiskStatsRequest, apiversion.Version) (*DiskStatsResponse, error)
	GetDiskNumberByName(context.Context, *GetDiskNumberByNameRequest, apiversion.Version) (*GetDiskNumberByNameResponse, error)
	ListDiskIDs(context.Context, *ListDiskIDsRequest, apiversion.Version) (*ListDiskIDsResponse, error)
	ListDiskLocations(context.Context, *ListDiskLocationsRequest, apiversion.Version) (*ListDiskLocationsResponse, error)
	PartitionDisk(context.Context, *PartitionDiskRequest, apiversion.Version) (*PartitionDiskResponse, error)
	Rescan(context.Context, *RescanRequest, apiversion.Version) (*RescanResponse, error)
	SetAttachState(context.Context, *SetAttachStateRequest, apiversion.Version) (*SetAttachStateResponse, error)
}
