// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta2 "github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta2"
	internal "github.com/kubernetes-csi/csi-proxy/internal/server/filesystem/internal"
)

func autoConvert_v1beta2_CreateSymlinkRequest_To_internal_CreateSymlinkRequest(in *v1beta2.CreateSymlinkRequest, out *internal.CreateSymlinkRequest) error {
	out.SourcePath = in.SourcePath
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_v1beta2_CreateSymlinkRequest_To_internal_CreateSymlinkRequest is an autogenerated conversion function.
func Convert_v1beta2_CreateSymlinkRequest_To_internal_CreateSymlinkRequest(in *v1beta2.CreateSymlinkRequest, out *internal.CreateSymlinkRequest) error {
	return autoConvert_v1beta2_CreateSymlinkRequest_To_internal_CreateSymlinkRequest(in, out)
}

func autoConvert_internal_CreateSymlinkRequest_To_v1beta2_CreateSymlinkRequest(in *internal.CreateSymlinkRequest, out *v1beta2.CreateSymlinkRequest) error {
	out.SourcePath = in.SourcePath
	out.TargetPath = in.TargetPath
	return nil
}

// Convert_internal_CreateSymlinkRequest_To_v1beta2_CreateSymlinkRequest is an autogenerated conversion function.
func Convert_internal_CreateSymlinkRequest_To_v1beta2_CreateSymlinkRequest(in *internal.CreateSymlinkRequest, out *v1beta2.CreateSymlinkRequest) error {
	return autoConvert_internal_CreateSymlinkRequest_To_v1beta2_CreateSymlinkRequest(in, out)
}

func autoConvert_v1beta2_CreateSymlinkResponse_To_internal_CreateSymlinkResponse(in *v1beta2.CreateSymlinkResponse, out *internal.CreateSymlinkResponse) error {
	return nil
}

// Convert_v1beta2_CreateSymlinkResponse_To_internal_CreateSymlinkResponse is an autogenerated conversion function.
func Convert_v1beta2_CreateSymlinkResponse_To_internal_CreateSymlinkResponse(in *v1beta2.CreateSymlinkResponse, out *internal.CreateSymlinkResponse) error {
	return autoConvert_v1beta2_CreateSymlinkResponse_To_internal_CreateSymlinkResponse(in, out)
}

func autoConvert_internal_CreateSymlinkResponse_To_v1beta2_CreateSymlinkResponse(in *internal.CreateSymlinkResponse, out *v1beta2.CreateSymlinkResponse) error {
	return nil
}

// Convert_internal_CreateSymlinkResponse_To_v1beta2_CreateSymlinkResponse is an autogenerated conversion function.
func Convert_internal_CreateSymlinkResponse_To_v1beta2_CreateSymlinkResponse(in *internal.CreateSymlinkResponse, out *v1beta2.CreateSymlinkResponse) error {
	return autoConvert_internal_CreateSymlinkResponse_To_v1beta2_CreateSymlinkResponse(in, out)
}

func autoConvert_v1beta2_IsSymlinkRequest_To_internal_IsSymlinkRequest(in *v1beta2.IsSymlinkRequest, out *internal.IsSymlinkRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_v1beta2_IsSymlinkRequest_To_internal_IsSymlinkRequest is an autogenerated conversion function.
func Convert_v1beta2_IsSymlinkRequest_To_internal_IsSymlinkRequest(in *v1beta2.IsSymlinkRequest, out *internal.IsSymlinkRequest) error {
	return autoConvert_v1beta2_IsSymlinkRequest_To_internal_IsSymlinkRequest(in, out)
}

func autoConvert_internal_IsSymlinkRequest_To_v1beta2_IsSymlinkRequest(in *internal.IsSymlinkRequest, out *v1beta2.IsSymlinkRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_internal_IsSymlinkRequest_To_v1beta2_IsSymlinkRequest is an autogenerated conversion function.
func Convert_internal_IsSymlinkRequest_To_v1beta2_IsSymlinkRequest(in *internal.IsSymlinkRequest, out *v1beta2.IsSymlinkRequest) error {
	return autoConvert_internal_IsSymlinkRequest_To_v1beta2_IsSymlinkRequest(in, out)
}

func autoConvert_v1beta2_IsSymlinkResponse_To_internal_IsSymlinkResponse(in *v1beta2.IsSymlinkResponse, out *internal.IsSymlinkResponse) error {
	out.IsSymlink = in.IsSymlink
	return nil
}

// Convert_v1beta2_IsSymlinkResponse_To_internal_IsSymlinkResponse is an autogenerated conversion function.
func Convert_v1beta2_IsSymlinkResponse_To_internal_IsSymlinkResponse(in *v1beta2.IsSymlinkResponse, out *internal.IsSymlinkResponse) error {
	return autoConvert_v1beta2_IsSymlinkResponse_To_internal_IsSymlinkResponse(in, out)
}

func autoConvert_internal_IsSymlinkResponse_To_v1beta2_IsSymlinkResponse(in *internal.IsSymlinkResponse, out *v1beta2.IsSymlinkResponse) error {
	out.IsSymlink = in.IsSymlink
	return nil
}

// Convert_internal_IsSymlinkResponse_To_v1beta2_IsSymlinkResponse is an autogenerated conversion function.
func Convert_internal_IsSymlinkResponse_To_v1beta2_IsSymlinkResponse(in *internal.IsSymlinkResponse, out *v1beta2.IsSymlinkResponse) error {
	return autoConvert_internal_IsSymlinkResponse_To_v1beta2_IsSymlinkResponse(in, out)
}

func autoConvert_v1beta2_MkdirRequest_To_internal_MkdirRequest(in *v1beta2.MkdirRequest, out *internal.MkdirRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_v1beta2_MkdirRequest_To_internal_MkdirRequest is an autogenerated conversion function.
func Convert_v1beta2_MkdirRequest_To_internal_MkdirRequest(in *v1beta2.MkdirRequest, out *internal.MkdirRequest) error {
	return autoConvert_v1beta2_MkdirRequest_To_internal_MkdirRequest(in, out)
}

func autoConvert_internal_MkdirRequest_To_v1beta2_MkdirRequest(in *internal.MkdirRequest, out *v1beta2.MkdirRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_internal_MkdirRequest_To_v1beta2_MkdirRequest is an autogenerated conversion function.
func Convert_internal_MkdirRequest_To_v1beta2_MkdirRequest(in *internal.MkdirRequest, out *v1beta2.MkdirRequest) error {
	return autoConvert_internal_MkdirRequest_To_v1beta2_MkdirRequest(in, out)
}

func autoConvert_v1beta2_MkdirResponse_To_internal_MkdirResponse(in *v1beta2.MkdirResponse, out *internal.MkdirResponse) error {
	return nil
}

// Convert_v1beta2_MkdirResponse_To_internal_MkdirResponse is an autogenerated conversion function.
func Convert_v1beta2_MkdirResponse_To_internal_MkdirResponse(in *v1beta2.MkdirResponse, out *internal.MkdirResponse) error {
	return autoConvert_v1beta2_MkdirResponse_To_internal_MkdirResponse(in, out)
}

func autoConvert_internal_MkdirResponse_To_v1beta2_MkdirResponse(in *internal.MkdirResponse, out *v1beta2.MkdirResponse) error {
	return nil
}

// Convert_internal_MkdirResponse_To_v1beta2_MkdirResponse is an autogenerated conversion function.
func Convert_internal_MkdirResponse_To_v1beta2_MkdirResponse(in *internal.MkdirResponse, out *v1beta2.MkdirResponse) error {
	return autoConvert_internal_MkdirResponse_To_v1beta2_MkdirResponse(in, out)
}

func autoConvert_v1beta2_PathExistsRequest_To_internal_PathExistsRequest(in *v1beta2.PathExistsRequest, out *internal.PathExistsRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_v1beta2_PathExistsRequest_To_internal_PathExistsRequest is an autogenerated conversion function.
func Convert_v1beta2_PathExistsRequest_To_internal_PathExistsRequest(in *v1beta2.PathExistsRequest, out *internal.PathExistsRequest) error {
	return autoConvert_v1beta2_PathExistsRequest_To_internal_PathExistsRequest(in, out)
}

func autoConvert_internal_PathExistsRequest_To_v1beta2_PathExistsRequest(in *internal.PathExistsRequest, out *v1beta2.PathExistsRequest) error {
	out.Path = in.Path
	return nil
}

// Convert_internal_PathExistsRequest_To_v1beta2_PathExistsRequest is an autogenerated conversion function.
func Convert_internal_PathExistsRequest_To_v1beta2_PathExistsRequest(in *internal.PathExistsRequest, out *v1beta2.PathExistsRequest) error {
	return autoConvert_internal_PathExistsRequest_To_v1beta2_PathExistsRequest(in, out)
}

func autoConvert_v1beta2_PathExistsResponse_To_internal_PathExistsResponse(in *v1beta2.PathExistsResponse, out *internal.PathExistsResponse) error {
	out.Exists = in.Exists
	return nil
}

// Convert_v1beta2_PathExistsResponse_To_internal_PathExistsResponse is an autogenerated conversion function.
func Convert_v1beta2_PathExistsResponse_To_internal_PathExistsResponse(in *v1beta2.PathExistsResponse, out *internal.PathExistsResponse) error {
	return autoConvert_v1beta2_PathExistsResponse_To_internal_PathExistsResponse(in, out)
}

func autoConvert_internal_PathExistsResponse_To_v1beta2_PathExistsResponse(in *internal.PathExistsResponse, out *v1beta2.PathExistsResponse) error {
	out.Exists = in.Exists
	return nil
}

// Convert_internal_PathExistsResponse_To_v1beta2_PathExistsResponse is an autogenerated conversion function.
func Convert_internal_PathExistsResponse_To_v1beta2_PathExistsResponse(in *internal.PathExistsResponse, out *v1beta2.PathExistsResponse) error {
	return autoConvert_internal_PathExistsResponse_To_v1beta2_PathExistsResponse(in, out)
}

func autoConvert_v1beta2_RmdirRequest_To_internal_RmdirRequest(in *v1beta2.RmdirRequest, out *internal.RmdirRequest) error {
	out.Path = in.Path
	out.Force = in.Force
	return nil
}

// Convert_v1beta2_RmdirRequest_To_internal_RmdirRequest is an autogenerated conversion function.
func Convert_v1beta2_RmdirRequest_To_internal_RmdirRequest(in *v1beta2.RmdirRequest, out *internal.RmdirRequest) error {
	return autoConvert_v1beta2_RmdirRequest_To_internal_RmdirRequest(in, out)
}

func autoConvert_internal_RmdirRequest_To_v1beta2_RmdirRequest(in *internal.RmdirRequest, out *v1beta2.RmdirRequest) error {
	out.Path = in.Path
	out.Force = in.Force
	return nil
}

// Convert_internal_RmdirRequest_To_v1beta2_RmdirRequest is an autogenerated conversion function.
func Convert_internal_RmdirRequest_To_v1beta2_RmdirRequest(in *internal.RmdirRequest, out *v1beta2.RmdirRequest) error {
	return autoConvert_internal_RmdirRequest_To_v1beta2_RmdirRequest(in, out)
}

func autoConvert_v1beta2_RmdirResponse_To_internal_RmdirResponse(in *v1beta2.RmdirResponse, out *internal.RmdirResponse) error {
	return nil
}

// Convert_v1beta2_RmdirResponse_To_internal_RmdirResponse is an autogenerated conversion function.
func Convert_v1beta2_RmdirResponse_To_internal_RmdirResponse(in *v1beta2.RmdirResponse, out *internal.RmdirResponse) error {
	return autoConvert_v1beta2_RmdirResponse_To_internal_RmdirResponse(in, out)
}

func autoConvert_internal_RmdirResponse_To_v1beta2_RmdirResponse(in *internal.RmdirResponse, out *v1beta2.RmdirResponse) error {
	return nil
}

// Convert_internal_RmdirResponse_To_v1beta2_RmdirResponse is an autogenerated conversion function.
func Convert_internal_RmdirResponse_To_v1beta2_RmdirResponse(in *internal.RmdirResponse, out *v1beta2.RmdirResponse) error {
	return autoConvert_internal_RmdirResponse_To_v1beta2_RmdirResponse(in, out)
}
