// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1beta2

import (
	"context"

	"github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta2"
	"github.com/kubernetes-csi/csi-proxy/client/apiversion"
	"github.com/kubernetes-csi/csi-proxy/internal/server/filesystem/internal"
	"google.golang.org/grpc"
)

var version = apiversion.NewVersionOrPanic("v1beta2")

type versionedAPI struct {
	apiGroupServer internal.ServerInterface
}

func NewVersionedServer(apiGroupServer internal.ServerInterface) internal.VersionedAPI {
	return &versionedAPI{
		apiGroupServer: apiGroupServer,
	}
}

func (s *versionedAPI) Register(grpcServer *grpc.Server) {
	v1beta2.RegisterFilesystemServer(grpcServer, s)
}

func (s *versionedAPI) CreateSymlink(context context.Context, versionedRequest *v1beta2.CreateSymlinkRequest) (*v1beta2.CreateSymlinkResponse, error) {
	request := &internal.CreateSymlinkRequest{}
	if err := Convert_v1beta2_CreateSymlinkRequest_To_internal_CreateSymlinkRequest(versionedRequest, request); err != nil {
		return nil, err
	}

	response, err := s.apiGroupServer.CreateSymlink(context, request, version)
	if err != nil {
		return nil, err
	}

	versionedResponse := &v1beta2.CreateSymlinkResponse{}
	if err := Convert_internal_CreateSymlinkResponse_To_v1beta2_CreateSymlinkResponse(response, versionedResponse); err != nil {
		return nil, err
	}

	return versionedResponse, err
}

func (s *versionedAPI) IsSymlink(context context.Context, versionedRequest *v1beta2.IsSymlinkRequest) (*v1beta2.IsSymlinkResponse, error) {
	request := &internal.IsSymlinkRequest{}
	if err := Convert_v1beta2_IsSymlinkRequest_To_internal_IsSymlinkRequest(versionedRequest, request); err != nil {
		return nil, err
	}

	response, err := s.apiGroupServer.IsSymlink(context, request, version)
	if err != nil {
		return nil, err
	}

	versionedResponse := &v1beta2.IsSymlinkResponse{}
	if err := Convert_internal_IsSymlinkResponse_To_v1beta2_IsSymlinkResponse(response, versionedResponse); err != nil {
		return nil, err
	}

	return versionedResponse, err
}

func (s *versionedAPI) Mkdir(context context.Context, versionedRequest *v1beta2.MkdirRequest) (*v1beta2.MkdirResponse, error) {
	request := &internal.MkdirRequest{}
	if err := Convert_v1beta2_MkdirRequest_To_internal_MkdirRequest(versionedRequest, request); err != nil {
		return nil, err
	}

	response, err := s.apiGroupServer.Mkdir(context, request, version)
	if err != nil {
		return nil, err
	}

	versionedResponse := &v1beta2.MkdirResponse{}
	if err := Convert_internal_MkdirResponse_To_v1beta2_MkdirResponse(response, versionedResponse); err != nil {
		return nil, err
	}

	return versionedResponse, err
}

func (s *versionedAPI) PathExists(context context.Context, versionedRequest *v1beta2.PathExistsRequest) (*v1beta2.PathExistsResponse, error) {
	request := &internal.PathExistsRequest{}
	if err := Convert_v1beta2_PathExistsRequest_To_internal_PathExistsRequest(versionedRequest, request); err != nil {
		return nil, err
	}

	response, err := s.apiGroupServer.PathExists(context, request, version)
	if err != nil {
		return nil, err
	}

	versionedResponse := &v1beta2.PathExistsResponse{}
	if err := Convert_internal_PathExistsResponse_To_v1beta2_PathExistsResponse(response, versionedResponse); err != nil {
		return nil, err
	}

	return versionedResponse, err
}

func (s *versionedAPI) Rmdir(context context.Context, versionedRequest *v1beta2.RmdirRequest) (*v1beta2.RmdirResponse, error) {
	request := &internal.RmdirRequest{}
	if err := Convert_v1beta2_RmdirRequest_To_internal_RmdirRequest(versionedRequest, request); err != nil {
		return nil, err
	}

	response, err := s.apiGroupServer.Rmdir(context, request, version)
	if err != nil {
		return nil, err
	}

	versionedResponse := &v1beta2.RmdirResponse{}
	if err := Convert_internal_RmdirResponse_To_v1beta2_RmdirResponse(response, versionedResponse); err != nil {
		return nil, err
	}

	return versionedResponse, err
}
