// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "github.com/kubernetes-csi/csi-proxy/client/api/iscsi/v1alpha1"
	impl "github.com/kubernetes-csi/csi-proxy/pkg/server/iscsi/impl"
)

func autoConvert_v1alpha1_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in *v1alpha1.AddTargetPortalRequest, out *impl.AddTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha1_AddTargetPortalRequest_To_impl_AddTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha1_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in *v1alpha1.AddTargetPortalRequest, out *impl.AddTargetPortalRequest) error {
	return autoConvert_v1alpha1_AddTargetPortalRequest_To_impl_AddTargetPortalRequest(in, out)
}

func autoConvert_impl_AddTargetPortalRequest_To_v1alpha1_AddTargetPortalRequest(in *impl.AddTargetPortalRequest, out *v1alpha1.AddTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_AddTargetPortalRequest_To_v1alpha1_AddTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_AddTargetPortalRequest_To_v1alpha1_AddTargetPortalRequest(in *impl.AddTargetPortalRequest, out *v1alpha1.AddTargetPortalRequest) error {
	return autoConvert_impl_AddTargetPortalRequest_To_v1alpha1_AddTargetPortalRequest(in, out)
}

func autoConvert_v1alpha1_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in *v1alpha1.AddTargetPortalResponse, out *impl.AddTargetPortalResponse) error {
	return nil
}

// Convert_v1alpha1_AddTargetPortalResponse_To_impl_AddTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha1_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in *v1alpha1.AddTargetPortalResponse, out *impl.AddTargetPortalResponse) error {
	return autoConvert_v1alpha1_AddTargetPortalResponse_To_impl_AddTargetPortalResponse(in, out)
}

func autoConvert_impl_AddTargetPortalResponse_To_v1alpha1_AddTargetPortalResponse(in *impl.AddTargetPortalResponse, out *v1alpha1.AddTargetPortalResponse) error {
	return nil
}

// Convert_impl_AddTargetPortalResponse_To_v1alpha1_AddTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_AddTargetPortalResponse_To_v1alpha1_AddTargetPortalResponse(in *impl.AddTargetPortalResponse, out *v1alpha1.AddTargetPortalResponse) error {
	return autoConvert_impl_AddTargetPortalResponse_To_v1alpha1_AddTargetPortalResponse(in, out)
}

func autoConvert_v1alpha1_ConnectTargetRequest_To_impl_ConnectTargetRequest(in *v1alpha1.ConnectTargetRequest, out *impl.ConnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	out.AuthType = impl.AuthenticationType(in.AuthType)
	out.ChapUsername = in.ChapUsername
	out.ChapSecret = in.ChapSecret
	return nil
}

// Convert_v1alpha1_ConnectTargetRequest_To_impl_ConnectTargetRequest is an autogenerated conversion function.
func Convert_v1alpha1_ConnectTargetRequest_To_impl_ConnectTargetRequest(in *v1alpha1.ConnectTargetRequest, out *impl.ConnectTargetRequest) error {
	return autoConvert_v1alpha1_ConnectTargetRequest_To_impl_ConnectTargetRequest(in, out)
}

func autoConvert_impl_ConnectTargetRequest_To_v1alpha1_ConnectTargetRequest(in *impl.ConnectTargetRequest, out *v1alpha1.ConnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	out.AuthType = v1alpha1.AuthenticationType(in.AuthType)
	out.ChapUsername = in.ChapUsername
	out.ChapSecret = in.ChapSecret
	return nil
}

// Convert_impl_ConnectTargetRequest_To_v1alpha1_ConnectTargetRequest is an autogenerated conversion function.
func Convert_impl_ConnectTargetRequest_To_v1alpha1_ConnectTargetRequest(in *impl.ConnectTargetRequest, out *v1alpha1.ConnectTargetRequest) error {
	return autoConvert_impl_ConnectTargetRequest_To_v1alpha1_ConnectTargetRequest(in, out)
}

func autoConvert_v1alpha1_ConnectTargetResponse_To_impl_ConnectTargetResponse(in *v1alpha1.ConnectTargetResponse, out *impl.ConnectTargetResponse) error {
	return nil
}

// Convert_v1alpha1_ConnectTargetResponse_To_impl_ConnectTargetResponse is an autogenerated conversion function.
func Convert_v1alpha1_ConnectTargetResponse_To_impl_ConnectTargetResponse(in *v1alpha1.ConnectTargetResponse, out *impl.ConnectTargetResponse) error {
	return autoConvert_v1alpha1_ConnectTargetResponse_To_impl_ConnectTargetResponse(in, out)
}

func autoConvert_impl_ConnectTargetResponse_To_v1alpha1_ConnectTargetResponse(in *impl.ConnectTargetResponse, out *v1alpha1.ConnectTargetResponse) error {
	return nil
}

// Convert_impl_ConnectTargetResponse_To_v1alpha1_ConnectTargetResponse is an autogenerated conversion function.
func Convert_impl_ConnectTargetResponse_To_v1alpha1_ConnectTargetResponse(in *impl.ConnectTargetResponse, out *v1alpha1.ConnectTargetResponse) error {
	return autoConvert_impl_ConnectTargetResponse_To_v1alpha1_ConnectTargetResponse(in, out)
}

func autoConvert_v1alpha1_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in *v1alpha1.DisconnectTargetRequest, out *impl.DisconnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_v1alpha1_DisconnectTargetRequest_To_impl_DisconnectTargetRequest is an autogenerated conversion function.
func Convert_v1alpha1_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in *v1alpha1.DisconnectTargetRequest, out *impl.DisconnectTargetRequest) error {
	return autoConvert_v1alpha1_DisconnectTargetRequest_To_impl_DisconnectTargetRequest(in, out)
}

func autoConvert_impl_DisconnectTargetRequest_To_v1alpha1_DisconnectTargetRequest(in *impl.DisconnectTargetRequest, out *v1alpha1.DisconnectTargetRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_impl_DisconnectTargetRequest_To_v1alpha1_DisconnectTargetRequest is an autogenerated conversion function.
func Convert_impl_DisconnectTargetRequest_To_v1alpha1_DisconnectTargetRequest(in *impl.DisconnectTargetRequest, out *v1alpha1.DisconnectTargetRequest) error {
	return autoConvert_impl_DisconnectTargetRequest_To_v1alpha1_DisconnectTargetRequest(in, out)
}

func autoConvert_v1alpha1_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in *v1alpha1.DisconnectTargetResponse, out *impl.DisconnectTargetResponse) error {
	return nil
}

// Convert_v1alpha1_DisconnectTargetResponse_To_impl_DisconnectTargetResponse is an autogenerated conversion function.
func Convert_v1alpha1_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in *v1alpha1.DisconnectTargetResponse, out *impl.DisconnectTargetResponse) error {
	return autoConvert_v1alpha1_DisconnectTargetResponse_To_impl_DisconnectTargetResponse(in, out)
}

func autoConvert_impl_DisconnectTargetResponse_To_v1alpha1_DisconnectTargetResponse(in *impl.DisconnectTargetResponse, out *v1alpha1.DisconnectTargetResponse) error {
	return nil
}

// Convert_impl_DisconnectTargetResponse_To_v1alpha1_DisconnectTargetResponse is an autogenerated conversion function.
func Convert_impl_DisconnectTargetResponse_To_v1alpha1_DisconnectTargetResponse(in *impl.DisconnectTargetResponse, out *v1alpha1.DisconnectTargetResponse) error {
	return autoConvert_impl_DisconnectTargetResponse_To_v1alpha1_DisconnectTargetResponse(in, out)
}

func autoConvert_v1alpha1_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in *v1alpha1.DiscoverTargetPortalRequest, out *impl.DiscoverTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha1_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha1_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in *v1alpha1.DiscoverTargetPortalRequest, out *impl.DiscoverTargetPortalRequest) error {
	return autoConvert_v1alpha1_DiscoverTargetPortalRequest_To_impl_DiscoverTargetPortalRequest(in, out)
}

func autoConvert_impl_DiscoverTargetPortalRequest_To_v1alpha1_DiscoverTargetPortalRequest(in *impl.DiscoverTargetPortalRequest, out *v1alpha1.DiscoverTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_DiscoverTargetPortalRequest_To_v1alpha1_DiscoverTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_DiscoverTargetPortalRequest_To_v1alpha1_DiscoverTargetPortalRequest(in *impl.DiscoverTargetPortalRequest, out *v1alpha1.DiscoverTargetPortalRequest) error {
	return autoConvert_impl_DiscoverTargetPortalRequest_To_v1alpha1_DiscoverTargetPortalRequest(in, out)
}

func autoConvert_v1alpha1_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in *v1alpha1.DiscoverTargetPortalResponse, out *impl.DiscoverTargetPortalResponse) error {
	out.Iqns = *(*[]string)(unsafe.Pointer(&in.Iqns))
	return nil
}

// Convert_v1alpha1_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha1_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in *v1alpha1.DiscoverTargetPortalResponse, out *impl.DiscoverTargetPortalResponse) error {
	return autoConvert_v1alpha1_DiscoverTargetPortalResponse_To_impl_DiscoverTargetPortalResponse(in, out)
}

func autoConvert_impl_DiscoverTargetPortalResponse_To_v1alpha1_DiscoverTargetPortalResponse(in *impl.DiscoverTargetPortalResponse, out *v1alpha1.DiscoverTargetPortalResponse) error {
	out.Iqns = *(*[]string)(unsafe.Pointer(&in.Iqns))
	return nil
}

// Convert_impl_DiscoverTargetPortalResponse_To_v1alpha1_DiscoverTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_DiscoverTargetPortalResponse_To_v1alpha1_DiscoverTargetPortalResponse(in *impl.DiscoverTargetPortalResponse, out *v1alpha1.DiscoverTargetPortalResponse) error {
	return autoConvert_impl_DiscoverTargetPortalResponse_To_v1alpha1_DiscoverTargetPortalResponse(in, out)
}

func autoConvert_v1alpha1_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in *v1alpha1.GetTargetDisksRequest, out *impl.GetTargetDisksRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_v1alpha1_GetTargetDisksRequest_To_impl_GetTargetDisksRequest is an autogenerated conversion function.
func Convert_v1alpha1_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in *v1alpha1.GetTargetDisksRequest, out *impl.GetTargetDisksRequest) error {
	return autoConvert_v1alpha1_GetTargetDisksRequest_To_impl_GetTargetDisksRequest(in, out)
}

func autoConvert_impl_GetTargetDisksRequest_To_v1alpha1_GetTargetDisksRequest(in *impl.GetTargetDisksRequest, out *v1alpha1.GetTargetDisksRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	out.Iqn = in.Iqn
	return nil
}

// Convert_impl_GetTargetDisksRequest_To_v1alpha1_GetTargetDisksRequest is an autogenerated conversion function.
func Convert_impl_GetTargetDisksRequest_To_v1alpha1_GetTargetDisksRequest(in *impl.GetTargetDisksRequest, out *v1alpha1.GetTargetDisksRequest) error {
	return autoConvert_impl_GetTargetDisksRequest_To_v1alpha1_GetTargetDisksRequest(in, out)
}

func autoConvert_v1alpha1_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in *v1alpha1.GetTargetDisksResponse, out *impl.GetTargetDisksResponse) error {
	out.DiskIDs = *(*[]string)(unsafe.Pointer(&in.DiskIDs))
	return nil
}

// Convert_v1alpha1_GetTargetDisksResponse_To_impl_GetTargetDisksResponse is an autogenerated conversion function.
func Convert_v1alpha1_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in *v1alpha1.GetTargetDisksResponse, out *impl.GetTargetDisksResponse) error {
	return autoConvert_v1alpha1_GetTargetDisksResponse_To_impl_GetTargetDisksResponse(in, out)
}

func autoConvert_impl_GetTargetDisksResponse_To_v1alpha1_GetTargetDisksResponse(in *impl.GetTargetDisksResponse, out *v1alpha1.GetTargetDisksResponse) error {
	out.DiskIDs = *(*[]string)(unsafe.Pointer(&in.DiskIDs))
	return nil
}

// Convert_impl_GetTargetDisksResponse_To_v1alpha1_GetTargetDisksResponse is an autogenerated conversion function.
func Convert_impl_GetTargetDisksResponse_To_v1alpha1_GetTargetDisksResponse(in *impl.GetTargetDisksResponse, out *v1alpha1.GetTargetDisksResponse) error {
	return autoConvert_impl_GetTargetDisksResponse_To_v1alpha1_GetTargetDisksResponse(in, out)
}

func autoConvert_v1alpha1_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in *v1alpha1.ListTargetPortalsRequest, out *impl.ListTargetPortalsRequest) error {
	return nil
}

// Convert_v1alpha1_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest is an autogenerated conversion function.
func Convert_v1alpha1_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in *v1alpha1.ListTargetPortalsRequest, out *impl.ListTargetPortalsRequest) error {
	return autoConvert_v1alpha1_ListTargetPortalsRequest_To_impl_ListTargetPortalsRequest(in, out)
}

func autoConvert_impl_ListTargetPortalsRequest_To_v1alpha1_ListTargetPortalsRequest(in *impl.ListTargetPortalsRequest, out *v1alpha1.ListTargetPortalsRequest) error {
	return nil
}

// Convert_impl_ListTargetPortalsRequest_To_v1alpha1_ListTargetPortalsRequest is an autogenerated conversion function.
func Convert_impl_ListTargetPortalsRequest_To_v1alpha1_ListTargetPortalsRequest(in *impl.ListTargetPortalsRequest, out *v1alpha1.ListTargetPortalsRequest) error {
	return autoConvert_impl_ListTargetPortalsRequest_To_v1alpha1_ListTargetPortalsRequest(in, out)
}

func autoConvert_v1alpha1_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in *v1alpha1.ListTargetPortalsResponse, out *impl.ListTargetPortalsResponse) error {
	if in.TargetPortals != nil {
		in, out := &in.TargetPortals, &out.TargetPortals
		*out = make([]*impl.TargetPortal, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*&(*in)[i], *&(*out)[i]); err != nil {
				return err
			}
		}
	} else {
		out.TargetPortals = nil
	}
	return nil
}

// Convert_v1alpha1_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse is an autogenerated conversion function.
func Convert_v1alpha1_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in *v1alpha1.ListTargetPortalsResponse, out *impl.ListTargetPortalsResponse) error {
	return autoConvert_v1alpha1_ListTargetPortalsResponse_To_impl_ListTargetPortalsResponse(in, out)
}

// detected external conversion function
// Convert_impl_ListTargetPortalsResponse_To_v1alpha1_ListTargetPortalsResponse(in *impl.ListTargetPortalsResponse, out *v1alpha1.ListTargetPortalsResponse) error
// skipping generation of the auto function

func autoConvert_v1alpha1_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in *v1alpha1.RemoveTargetPortalRequest, out *impl.RemoveTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(impl.TargetPortal)
		if err := Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_v1alpha1_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest is an autogenerated conversion function.
func Convert_v1alpha1_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in *v1alpha1.RemoveTargetPortalRequest, out *impl.RemoveTargetPortalRequest) error {
	return autoConvert_v1alpha1_RemoveTargetPortalRequest_To_impl_RemoveTargetPortalRequest(in, out)
}

func autoConvert_impl_RemoveTargetPortalRequest_To_v1alpha1_RemoveTargetPortalRequest(in *impl.RemoveTargetPortalRequest, out *v1alpha1.RemoveTargetPortalRequest) error {
	if in.TargetPortal != nil {
		in, out := &in.TargetPortal, &out.TargetPortal
		*out = new(v1alpha1.TargetPortal)
		if err := Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(*in, *out); err != nil {
			return err
		}
	} else {
		out.TargetPortal = nil
	}
	return nil
}

// Convert_impl_RemoveTargetPortalRequest_To_v1alpha1_RemoveTargetPortalRequest is an autogenerated conversion function.
func Convert_impl_RemoveTargetPortalRequest_To_v1alpha1_RemoveTargetPortalRequest(in *impl.RemoveTargetPortalRequest, out *v1alpha1.RemoveTargetPortalRequest) error {
	return autoConvert_impl_RemoveTargetPortalRequest_To_v1alpha1_RemoveTargetPortalRequest(in, out)
}

func autoConvert_v1alpha1_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in *v1alpha1.RemoveTargetPortalResponse, out *impl.RemoveTargetPortalResponse) error {
	return nil
}

// Convert_v1alpha1_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse is an autogenerated conversion function.
func Convert_v1alpha1_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in *v1alpha1.RemoveTargetPortalResponse, out *impl.RemoveTargetPortalResponse) error {
	return autoConvert_v1alpha1_RemoveTargetPortalResponse_To_impl_RemoveTargetPortalResponse(in, out)
}

func autoConvert_impl_RemoveTargetPortalResponse_To_v1alpha1_RemoveTargetPortalResponse(in *impl.RemoveTargetPortalResponse, out *v1alpha1.RemoveTargetPortalResponse) error {
	return nil
}

// Convert_impl_RemoveTargetPortalResponse_To_v1alpha1_RemoveTargetPortalResponse is an autogenerated conversion function.
func Convert_impl_RemoveTargetPortalResponse_To_v1alpha1_RemoveTargetPortalResponse(in *impl.RemoveTargetPortalResponse, out *v1alpha1.RemoveTargetPortalResponse) error {
	return autoConvert_impl_RemoveTargetPortalResponse_To_v1alpha1_RemoveTargetPortalResponse(in, out)
}

func autoConvert_v1alpha1_TargetPortal_To_impl_TargetPortal(in *v1alpha1.TargetPortal, out *impl.TargetPortal) error {
	out.TargetAddress = in.TargetAddress
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1alpha1_TargetPortal_To_impl_TargetPortal is an autogenerated conversion function.
func Convert_v1alpha1_TargetPortal_To_impl_TargetPortal(in *v1alpha1.TargetPortal, out *impl.TargetPortal) error {
	return autoConvert_v1alpha1_TargetPortal_To_impl_TargetPortal(in, out)
}

func autoConvert_impl_TargetPortal_To_v1alpha1_TargetPortal(in *impl.TargetPortal, out *v1alpha1.TargetPortal) error {
	out.TargetAddress = in.TargetAddress
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_impl_TargetPortal_To_v1alpha1_TargetPortal is an autogenerated conversion function.
func Convert_impl_TargetPortal_To_v1alpha1_TargetPortal(in *impl.TargetPortal, out *v1alpha1.TargetPortal) error {
	return autoConvert_impl_TargetPortal_To_v1alpha1_TargetPortal(in, out)
}
