// Code generated by csi-proxy-api-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	v1 "github.com/kubernetes-csi/csi-proxy/client/api/disk/v1"
	internal "github.com/kubernetes-csi/csi-proxy/internal/server/disk/internal"
)

func autoConvert_v1_DiskIDs_To_internal_DiskIDs(in *v1.DiskIDs, out *internal.DiskIDs) error {
	out.Identifiers = *(*map[string]string)(unsafe.Pointer(&in.Identifiers))
	return nil
}

// Convert_v1_DiskIDs_To_internal_DiskIDs is an autogenerated conversion function.
func Convert_v1_DiskIDs_To_internal_DiskIDs(in *v1.DiskIDs, out *internal.DiskIDs) error {
	return autoConvert_v1_DiskIDs_To_internal_DiskIDs(in, out)
}

func autoConvert_internal_DiskIDs_To_v1_DiskIDs(in *internal.DiskIDs, out *v1.DiskIDs) error {
	out.Identifiers = *(*map[string]string)(unsafe.Pointer(&in.Identifiers))
	return nil
}

// Convert_internal_DiskIDs_To_v1_DiskIDs is an autogenerated conversion function.
func Convert_internal_DiskIDs_To_v1_DiskIDs(in *internal.DiskIDs, out *v1.DiskIDs) error {
	return autoConvert_internal_DiskIDs_To_v1_DiskIDs(in, out)
}

func autoConvert_v1_DiskLocation_To_internal_DiskLocation(in *v1.DiskLocation, out *internal.DiskLocation) error {
	out.Adapter = in.Adapter
	out.Bus = in.Bus
	out.Target = in.Target
	out.LUNID = in.LUNID
	return nil
}

// Convert_v1_DiskLocation_To_internal_DiskLocation is an autogenerated conversion function.
func Convert_v1_DiskLocation_To_internal_DiskLocation(in *v1.DiskLocation, out *internal.DiskLocation) error {
	return autoConvert_v1_DiskLocation_To_internal_DiskLocation(in, out)
}

func autoConvert_internal_DiskLocation_To_v1_DiskLocation(in *internal.DiskLocation, out *v1.DiskLocation) error {
	out.Adapter = in.Adapter
	out.Bus = in.Bus
	out.Target = in.Target
	out.LUNID = in.LUNID
	return nil
}

// Convert_internal_DiskLocation_To_v1_DiskLocation is an autogenerated conversion function.
func Convert_internal_DiskLocation_To_v1_DiskLocation(in *internal.DiskLocation, out *v1.DiskLocation) error {
	return autoConvert_internal_DiskLocation_To_v1_DiskLocation(in, out)
}

func autoConvert_v1_DiskStatsRequest_To_internal_DiskStatsRequest(in *v1.DiskStatsRequest, out *internal.DiskStatsRequest) error {
	out.DiskID = in.DiskID
	return nil
}

func autoConvert_internal_DiskStatsRequest_To_v1_DiskStatsRequest(in *internal.DiskStatsRequest, out *v1.DiskStatsRequest) error {
	out.DiskID = in.DiskID
	return nil
}

// Convert_internal_DiskStatsRequest_To_v1_DiskStatsRequest is an autogenerated conversion function.
func Convert_internal_DiskStatsRequest_To_v1_DiskStatsRequest(in *internal.DiskStatsRequest, out *v1.DiskStatsRequest) error {
	return autoConvert_internal_DiskStatsRequest_To_v1_DiskStatsRequest(in, out)
}

func autoConvert_v1_DiskStatsResponse_To_internal_DiskStatsResponse(in *v1.DiskStatsResponse, out *internal.DiskStatsResponse) error {
	out.DiskSize = in.DiskSize
	return nil
}

// Convert_v1_DiskStatsResponse_To_internal_DiskStatsResponse is an autogenerated conversion function.
func Convert_v1_DiskStatsResponse_To_internal_DiskStatsResponse(in *v1.DiskStatsResponse, out *internal.DiskStatsResponse) error {
	return autoConvert_v1_DiskStatsResponse_To_internal_DiskStatsResponse(in, out)
}

func autoConvert_internal_DiskStatsResponse_To_v1_DiskStatsResponse(in *internal.DiskStatsResponse, out *v1.DiskStatsResponse) error {
	out.DiskSize = in.DiskSize
	return nil
}

func autoConvert_v1_GetAttachStateRequest_To_internal_GetAttachStateRequest(in *v1.GetAttachStateRequest, out *internal.GetAttachStateRequest) error {
	out.DiskID = in.DiskID
	return nil
}

// Convert_v1_GetAttachStateRequest_To_internal_GetAttachStateRequest is an autogenerated conversion function.
func Convert_v1_GetAttachStateRequest_To_internal_GetAttachStateRequest(in *v1.GetAttachStateRequest, out *internal.GetAttachStateRequest) error {
	return autoConvert_v1_GetAttachStateRequest_To_internal_GetAttachStateRequest(in, out)
}

func autoConvert_internal_GetAttachStateRequest_To_v1_GetAttachStateRequest(in *internal.GetAttachStateRequest, out *v1.GetAttachStateRequest) error {
	out.DiskID = in.DiskID
	return nil
}

// Convert_internal_GetAttachStateRequest_To_v1_GetAttachStateRequest is an autogenerated conversion function.
func Convert_internal_GetAttachStateRequest_To_v1_GetAttachStateRequest(in *internal.GetAttachStateRequest, out *v1.GetAttachStateRequest) error {
	return autoConvert_internal_GetAttachStateRequest_To_v1_GetAttachStateRequest(in, out)
}

func autoConvert_v1_GetAttachStateResponse_To_internal_GetAttachStateResponse(in *v1.GetAttachStateResponse, out *internal.GetAttachStateResponse) error {
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_v1_GetAttachStateResponse_To_internal_GetAttachStateResponse is an autogenerated conversion function.
func Convert_v1_GetAttachStateResponse_To_internal_GetAttachStateResponse(in *v1.GetAttachStateResponse, out *internal.GetAttachStateResponse) error {
	return autoConvert_v1_GetAttachStateResponse_To_internal_GetAttachStateResponse(in, out)
}

func autoConvert_internal_GetAttachStateResponse_To_v1_GetAttachStateResponse(in *internal.GetAttachStateResponse, out *v1.GetAttachStateResponse) error {
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_internal_GetAttachStateResponse_To_v1_GetAttachStateResponse is an autogenerated conversion function.
func Convert_internal_GetAttachStateResponse_To_v1_GetAttachStateResponse(in *internal.GetAttachStateResponse, out *v1.GetAttachStateResponse) error {
	return autoConvert_internal_GetAttachStateResponse_To_v1_GetAttachStateResponse(in, out)
}

func autoConvert_v1_ListDiskIDsRequest_To_internal_ListDiskIDsRequest(in *v1.ListDiskIDsRequest, out *internal.ListDiskIDsRequest) error {
	return nil
}

// Convert_v1_ListDiskIDsRequest_To_internal_ListDiskIDsRequest is an autogenerated conversion function.
func Convert_v1_ListDiskIDsRequest_To_internal_ListDiskIDsRequest(in *v1.ListDiskIDsRequest, out *internal.ListDiskIDsRequest) error {
	return autoConvert_v1_ListDiskIDsRequest_To_internal_ListDiskIDsRequest(in, out)
}

func autoConvert_internal_ListDiskIDsRequest_To_v1_ListDiskIDsRequest(in *internal.ListDiskIDsRequest, out *v1.ListDiskIDsRequest) error {
	return nil
}

// Convert_internal_ListDiskIDsRequest_To_v1_ListDiskIDsRequest is an autogenerated conversion function.
func Convert_internal_ListDiskIDsRequest_To_v1_ListDiskIDsRequest(in *internal.ListDiskIDsRequest, out *v1.ListDiskIDsRequest) error {
	return autoConvert_internal_ListDiskIDsRequest_To_v1_ListDiskIDsRequest(in, out)
}

func autoConvert_v1_ListDiskIDsResponse_To_internal_ListDiskIDsResponse(in *v1.ListDiskIDsResponse, out *internal.ListDiskIDsResponse) error {
	if in.DiskIDs != nil {
		in, out := &in.DiskIDs, &out.DiskIDs
		*out = make(map[string]*internal.DiskIDs, len(*in))
		for key, val := range *in {
			newVal := new(*internal.DiskIDs)
			if err := Convert_v1_DiskIDs_To_internal_DiskIDs(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskIDs = nil
	}
	return nil
}

// Convert_v1_ListDiskIDsResponse_To_internal_ListDiskIDsResponse is an autogenerated conversion function.
func Convert_v1_ListDiskIDsResponse_To_internal_ListDiskIDsResponse(in *v1.ListDiskIDsResponse, out *internal.ListDiskIDsResponse) error {
	return autoConvert_v1_ListDiskIDsResponse_To_internal_ListDiskIDsResponse(in, out)
}

func autoConvert_internal_ListDiskIDsResponse_To_v1_ListDiskIDsResponse(in *internal.ListDiskIDsResponse, out *v1.ListDiskIDsResponse) error {
	if in.DiskIDs != nil {
		in, out := &in.DiskIDs, &out.DiskIDs
		*out = make(map[string]*v1.DiskIDs, len(*in))
		for key, val := range *in {
			newVal := new(*v1.DiskIDs)
			if err := Convert_internal_DiskIDs_To_v1_DiskIDs(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskIDs = nil
	}
	return nil
}

func autoConvert_v1_ListDiskLocationsRequest_To_internal_ListDiskLocationsRequest(in *v1.ListDiskLocationsRequest, out *internal.ListDiskLocationsRequest) error {
	return nil
}

// Convert_v1_ListDiskLocationsRequest_To_internal_ListDiskLocationsRequest is an autogenerated conversion function.
func Convert_v1_ListDiskLocationsRequest_To_internal_ListDiskLocationsRequest(in *v1.ListDiskLocationsRequest, out *internal.ListDiskLocationsRequest) error {
	return autoConvert_v1_ListDiskLocationsRequest_To_internal_ListDiskLocationsRequest(in, out)
}

func autoConvert_internal_ListDiskLocationsRequest_To_v1_ListDiskLocationsRequest(in *internal.ListDiskLocationsRequest, out *v1.ListDiskLocationsRequest) error {
	return nil
}

// Convert_internal_ListDiskLocationsRequest_To_v1_ListDiskLocationsRequest is an autogenerated conversion function.
func Convert_internal_ListDiskLocationsRequest_To_v1_ListDiskLocationsRequest(in *internal.ListDiskLocationsRequest, out *v1.ListDiskLocationsRequest) error {
	return autoConvert_internal_ListDiskLocationsRequest_To_v1_ListDiskLocationsRequest(in, out)
}

func autoConvert_v1_ListDiskLocationsResponse_To_internal_ListDiskLocationsResponse(in *v1.ListDiskLocationsResponse, out *internal.ListDiskLocationsResponse) error {
	if in.DiskLocations != nil {
		in, out := &in.DiskLocations, &out.DiskLocations
		*out = make(map[string]*internal.DiskLocation, len(*in))
		for key, val := range *in {
			newVal := new(*internal.DiskLocation)
			if err := Convert_v1_DiskLocation_To_internal_DiskLocation(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskLocations = nil
	}
	return nil
}

// Convert_v1_ListDiskLocationsResponse_To_internal_ListDiskLocationsResponse is an autogenerated conversion function.
func Convert_v1_ListDiskLocationsResponse_To_internal_ListDiskLocationsResponse(in *v1.ListDiskLocationsResponse, out *internal.ListDiskLocationsResponse) error {
	return autoConvert_v1_ListDiskLocationsResponse_To_internal_ListDiskLocationsResponse(in, out)
}

func autoConvert_internal_ListDiskLocationsResponse_To_v1_ListDiskLocationsResponse(in *internal.ListDiskLocationsResponse, out *v1.ListDiskLocationsResponse) error {
	if in.DiskLocations != nil {
		in, out := &in.DiskLocations, &out.DiskLocations
		*out = make(map[string]*v1.DiskLocation, len(*in))
		for key, val := range *in {
			newVal := new(*v1.DiskLocation)
			if err := Convert_internal_DiskLocation_To_v1_DiskLocation(*&val, *newVal); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.DiskLocations = nil
	}
	return nil
}

func autoConvert_v1_PartitionDiskRequest_To_internal_PartitionDiskRequest(in *v1.PartitionDiskRequest, out *internal.PartitionDiskRequest) error {
	out.DiskID = in.DiskID
	return nil
}

// Convert_v1_PartitionDiskRequest_To_internal_PartitionDiskRequest is an autogenerated conversion function.
func Convert_v1_PartitionDiskRequest_To_internal_PartitionDiskRequest(in *v1.PartitionDiskRequest, out *internal.PartitionDiskRequest) error {
	return autoConvert_v1_PartitionDiskRequest_To_internal_PartitionDiskRequest(in, out)
}

func autoConvert_internal_PartitionDiskRequest_To_v1_PartitionDiskRequest(in *internal.PartitionDiskRequest, out *v1.PartitionDiskRequest) error {
	out.DiskID = in.DiskID
	return nil
}

// Convert_internal_PartitionDiskRequest_To_v1_PartitionDiskRequest is an autogenerated conversion function.
func Convert_internal_PartitionDiskRequest_To_v1_PartitionDiskRequest(in *internal.PartitionDiskRequest, out *v1.PartitionDiskRequest) error {
	return autoConvert_internal_PartitionDiskRequest_To_v1_PartitionDiskRequest(in, out)
}

func autoConvert_v1_PartitionDiskResponse_To_internal_PartitionDiskResponse(in *v1.PartitionDiskResponse, out *internal.PartitionDiskResponse) error {
	return nil
}

// Convert_v1_PartitionDiskResponse_To_internal_PartitionDiskResponse is an autogenerated conversion function.
func Convert_v1_PartitionDiskResponse_To_internal_PartitionDiskResponse(in *v1.PartitionDiskResponse, out *internal.PartitionDiskResponse) error {
	return autoConvert_v1_PartitionDiskResponse_To_internal_PartitionDiskResponse(in, out)
}

func autoConvert_internal_PartitionDiskResponse_To_v1_PartitionDiskResponse(in *internal.PartitionDiskResponse, out *v1.PartitionDiskResponse) error {
	return nil
}

// Convert_internal_PartitionDiskResponse_To_v1_PartitionDiskResponse is an autogenerated conversion function.
func Convert_internal_PartitionDiskResponse_To_v1_PartitionDiskResponse(in *internal.PartitionDiskResponse, out *v1.PartitionDiskResponse) error {
	return autoConvert_internal_PartitionDiskResponse_To_v1_PartitionDiskResponse(in, out)
}

func autoConvert_v1_RescanRequest_To_internal_RescanRequest(in *v1.RescanRequest, out *internal.RescanRequest) error {
	return nil
}

// Convert_v1_RescanRequest_To_internal_RescanRequest is an autogenerated conversion function.
func Convert_v1_RescanRequest_To_internal_RescanRequest(in *v1.RescanRequest, out *internal.RescanRequest) error {
	return autoConvert_v1_RescanRequest_To_internal_RescanRequest(in, out)
}

func autoConvert_internal_RescanRequest_To_v1_RescanRequest(in *internal.RescanRequest, out *v1.RescanRequest) error {
	return nil
}

// Convert_internal_RescanRequest_To_v1_RescanRequest is an autogenerated conversion function.
func Convert_internal_RescanRequest_To_v1_RescanRequest(in *internal.RescanRequest, out *v1.RescanRequest) error {
	return autoConvert_internal_RescanRequest_To_v1_RescanRequest(in, out)
}

func autoConvert_v1_RescanResponse_To_internal_RescanResponse(in *v1.RescanResponse, out *internal.RescanResponse) error {
	return nil
}

// Convert_v1_RescanResponse_To_internal_RescanResponse is an autogenerated conversion function.
func Convert_v1_RescanResponse_To_internal_RescanResponse(in *v1.RescanResponse, out *internal.RescanResponse) error {
	return autoConvert_v1_RescanResponse_To_internal_RescanResponse(in, out)
}

func autoConvert_internal_RescanResponse_To_v1_RescanResponse(in *internal.RescanResponse, out *v1.RescanResponse) error {
	return nil
}

// Convert_internal_RescanResponse_To_v1_RescanResponse is an autogenerated conversion function.
func Convert_internal_RescanResponse_To_v1_RescanResponse(in *internal.RescanResponse, out *v1.RescanResponse) error {
	return autoConvert_internal_RescanResponse_To_v1_RescanResponse(in, out)
}

func autoConvert_v1_SetAttachStateRequest_To_internal_SetAttachStateRequest(in *v1.SetAttachStateRequest, out *internal.SetAttachStateRequest) error {
	out.DiskID = in.DiskID
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_v1_SetAttachStateRequest_To_internal_SetAttachStateRequest is an autogenerated conversion function.
func Convert_v1_SetAttachStateRequest_To_internal_SetAttachStateRequest(in *v1.SetAttachStateRequest, out *internal.SetAttachStateRequest) error {
	return autoConvert_v1_SetAttachStateRequest_To_internal_SetAttachStateRequest(in, out)
}

func autoConvert_internal_SetAttachStateRequest_To_v1_SetAttachStateRequest(in *internal.SetAttachStateRequest, out *v1.SetAttachStateRequest) error {
	out.DiskID = in.DiskID
	out.IsOnline = in.IsOnline
	return nil
}

// Convert_internal_SetAttachStateRequest_To_v1_SetAttachStateRequest is an autogenerated conversion function.
func Convert_internal_SetAttachStateRequest_To_v1_SetAttachStateRequest(in *internal.SetAttachStateRequest, out *v1.SetAttachStateRequest) error {
	return autoConvert_internal_SetAttachStateRequest_To_v1_SetAttachStateRequest(in, out)
}

func autoConvert_v1_SetAttachStateResponse_To_internal_SetAttachStateResponse(in *v1.SetAttachStateResponse, out *internal.SetAttachStateResponse) error {
	return nil
}

// Convert_v1_SetAttachStateResponse_To_internal_SetAttachStateResponse is an autogenerated conversion function.
func Convert_v1_SetAttachStateResponse_To_internal_SetAttachStateResponse(in *v1.SetAttachStateResponse, out *internal.SetAttachStateResponse) error {
	return autoConvert_v1_SetAttachStateResponse_To_internal_SetAttachStateResponse(in, out)
}

func autoConvert_internal_SetAttachStateResponse_To_v1_SetAttachStateResponse(in *internal.SetAttachStateResponse, out *v1.SetAttachStateResponse) error {
	return nil
}

// Convert_internal_SetAttachStateResponse_To_v1_SetAttachStateResponse is an autogenerated conversion function.
func Convert_internal_SetAttachStateResponse_To_v1_SetAttachStateResponse(in *internal.SetAttachStateResponse, out *v1.SetAttachStateResponse) error {
	return autoConvert_internal_SetAttachStateResponse_To_v1_SetAttachStateResponse(in, out)
}
